import { makeStyles } from '@material-ui/core/styles';

export const useStyles = makeStyles((theme) => ({
  buttonWrapper: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    padding: 5,
    paddingLeft: 20,
    paddingRight: 20,
    boxSizing: 'border-box',
    background: theme.palette.secondary.main,
    border: '1px solid rgba(0,0,0,0.1)',
    borderTop: '1px solid rgba(255,255,255,0.2)',
    borderLeft: '1px solid rgba(255,255,255,0.2)',
    borderRadius: 2,
  },
  delete: { background: theme.palette.error.main },
  disabled: { background: '#aaa', boxShadow: 'none' },
  title: {
    color: '#222',
    fontSize: '1rem',
    textAlign: 'center',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    fontWeight: 'bold',
    fontFamily: `'Special Elite', cursive`,
    paddingTop: 1,
  },
  titleWithIcon: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  titleIcon: {
    color: '#222',
    fontSize: '1rem',
    textAlign: 'center',
    marginRight: 5,
  },
  icon: { fontSize: '1rem' },
  circle: {
    background: theme.palette.secondary.main,
    borderRadius: '4px 0 0 4px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#fff',
    marginRight: 10,
    height: 26,
    width: 26,
  },
  ml: { marginLeft: 10 },
  mr: { marginRight: 10 },
  mb: { marginBottom: 10 },
  mt: { marginTop: 10 },
  fullWidth: { width: '100%' },
}));
