/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react';
import { useGLTF } from '@react-three/drei';
import Mesh from '../Mesh';
export default function Model({ props }) {
  const group = useRef();

  const { nodes } = useGLTF(`${props.gltfIn}`);

  return (
    <group ref={group} {...props} dispose={null}>
      <Mesh
        activeColor={props.activeColor}
        paintMode={props.paintMode}
        modelColors={props.modelColors}
        modelColorsRef={props.modelColorsRef}
        name="Cylinder"
        lightOne={props.lightOne}
        geometry={nodes.Cylinder.geometry}
        position={[0, 0.46, 0]}
        scale={[3.75, 0.04, 3.75]}
      />
      <Mesh
        activeColor={props.activeColor}
        paintMode={props.paintMode}
        modelColors={props.modelColors}
        modelColorsRef={props.modelColorsRef}
        name="Cylinder001"
        lightOne={props.lightOne}
        geometry={nodes.Cylinder001.geometry}
        position={[0, 0.46, 0]}
        scale={[3.75, 0.04, 3.75]}
      />
    </group>
  );
}
