/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Estoppel (https://sketchfab.com/estoppel)
created: Thu Sep 30 13:56:59 2021
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/52283077360f4244921af1a065899efc
title: Bolter
*/
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import Mesh from '../Mesh';

export default function Model({ props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/spacemarine/bolter/scene.gltf');
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-1.57, 0, 1.57]}>
        <group
          position={[-1537.98, -858.04, 426.92]}
          rotation={[1.11, -1.01, -0.4]}
        />
        <Mesh
          activeColor={props.activeColor.color}
          paintMode={props.paintMode}
          modelColors={props.modelColors}
          modelColorsRef={props.modelColorsRef}
          name="Material3"
          lightOne={props.lightOne}
          geometry={nodes.Material3.geometry}
        />
        <Mesh
          activeColor={props.activeColor.color}
          paintMode={props.paintMode}
          modelColors={props.modelColors}
          modelColorsRef={props.modelColorsRef}
          name="Material2"
          lightOne={props.lightOne}
          geometry={nodes.Material2.geometry}
        />
        <Mesh
          activeColor={props.activeColor.color}
          paintMode={props.paintMode}
          modelColors={props.modelColors}
          modelColorsRef={props.modelColorsRef}
          name="Material2_1"
          lightOne={props.lightOne}
          geometry={nodes.Material2_1.geometry}
        />
        <Mesh
          activeColor={props.activeColor.color}
          paintMode={props.paintMode}
          modelColors={props.modelColors}
          modelColorsRef={props.modelColorsRef}
          name="Material2_2"
          lightOne={props.lightOne}
          geometry={nodes.Material2_2.geometry}
        />
        <Mesh
          activeColor={props.activeColor.color}
          paintMode={props.paintMode}
          modelColors={props.modelColors}
          modelColorsRef={props.modelColorsRef}
          name="Material2_3"
          lightOne={props.lightOne}
          geometry={nodes.Material2_3.geometry}
        />
        <Mesh
          activeColor={props.activeColor.color}
          paintMode={props.paintMode}
          modelColors={props.modelColors}
          modelColorsRef={props.modelColorsRef}
          name="Material3_1"
          lightOne={props.lightOne}
          geometry={nodes.Material3_1.geometry}
        />
        <Mesh
          activeColor={props.activeColor.color}
          paintMode={props.paintMode}
          modelColors={props.modelColors}
          modelColorsRef={props.modelColorsRef}
          name="Material3_2"
          lightOne={props.lightOne}
          geometry={nodes.Material3_2.geometry}
        />
        <Mesh
          activeColor={props.activeColor.color}
          paintMode={props.paintMode}
          modelColors={props.modelColors}
          modelColorsRef={props.modelColorsRef}
          name="Material3_3"
          lightOne={props.lightOne}
          geometry={nodes.Material3_3.geometry}
        />
        <Mesh
          activeColor={props.activeColor.color}
          paintMode={props.paintMode}
          modelColors={props.modelColors}
          modelColorsRef={props.modelColorsRef}
          name="Material2_4"
          lightOne={props.lightOne}
          geometry={nodes.Material2_4.geometry}
        />
        <Mesh
          activeColor={props.activeColor.color}
          paintMode={props.paintMode}
          modelColors={props.modelColors}
          modelColorsRef={props.modelColorsRef}
          name="Material2_5"
          lightOne={props.lightOne}
          geometry={nodes.Material2_5.geometry}
        />
        <Mesh
          activeColor={props.activeColor.color}
          paintMode={props.paintMode}
          modelColors={props.modelColors}
          modelColorsRef={props.modelColorsRef}
          name="Material3_4"
          lightOne={props.lightOne}
          geometry={nodes.Material3_4.geometry}
        />
        <Mesh
          activeColor={props.activeColor.color}
          paintMode={props.paintMode}
          modelColors={props.modelColors}
          modelColorsRef={props.modelColorsRef}
          name="Material2_6"
          lightOne={props.lightOne}
          geometry={nodes.Material2_6.geometry}
        />
        <Mesh
          activeColor={props.activeColor.color}
          paintMode={props.paintMode}
          modelColors={props.modelColors}
          modelColorsRef={props.modelColorsRef}
          name="Material2_7"
          lightOne={props.lightOne}
          geometry={nodes.Material2_7.geometry}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/spacemarine/bolter/scene.gltf');
