/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Janovich (https://sketchfab.com/janovich3D)
created: Sat Oct  2 22:04:19 2021
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/space-marine-650166abbb3448e9adece85e30b59c06
title: Space Marine
*/

import React, { useRef, useEffect } from 'react';
import { useGLTF } from '@react-three/drei';

import * as THREE from 'three';

import Mesh from '../Mesh';
export default function Model({ props }) {
  const group = useRef();
  const { nodes } = useGLTF('spacemarine/sm_helmet/scene.gltf');
  const [decalNormal, setDecalNormal] = React.useState(null);

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <Mesh
            activeColor={props.activeColor.color}
            paintMode={props.paintMode}
            modelColors={props.modelColors}
            modelColorsRef={props.modelColorsRef}
            name="SM_topHelmet_mesh2_helmet1_0"
            lightOne={props.lightOne}
            geometry={nodes.SM_topHelmet_mesh2_helmet1_0.geometry}
          />
          <Mesh
            activeColor={props.activeColor.color}
            paintMode={props.paintMode}
            modelColors={props.modelColors}
            modelColorsRef={props.modelColorsRef}
            name="SM_frontHelmet01_mesh1_helmet1_0"
            lightOne={props.lightOne}
            geometry={nodes.SM_frontHelmet01_mesh1_helmet1_0.geometry}
          />
          <Mesh
            activeColor={props.activeColor.color}
            paintMode={props.paintMode}
            modelColors={props.modelColors}
            modelColorsRef={props.modelColorsRef}
            name="SM_frontHelmet01plate_mesh_mouth_0"
            lightOne={props.lightOne}
            geometry={nodes.SM_frontHelmet01plate_mesh_mouth_0.geometry}
            decals={props.decalSet}
          />
          <Mesh
            activeColor={props.activeColor.color}
            paintMode={props.paintMode}
            modelColors={props.modelColors}
            modelColorsRef={props.modelColorsRef}
            name="pTorus1_tubes_0"
            lightOne={props.lightOne}
            geometry={nodes.pTorus1_tubes_0.geometry}
          />
          <Mesh
            activeColor={props.activeColor.color}
            paintMode={props.paintMode}
            modelColors={props.modelColors}
            modelColorsRef={props.modelColorsRef}
            name="pTorus2_tubes_0"
            lightOne={props.lightOne}
            geometry={nodes.pTorus2_tubes_0.geometry}
          />
          <Mesh
            activeColor={props.activeColor.color}
            paintMode={props.paintMode}
            modelColors={props.modelColors}
            modelColorsRef={props.modelColorsRef}
            name="pTorus3_tubes_0"
            lightOne={props.lightOne}
            geometry={nodes.pTorus3_tubes_0.geometry}
          />
          <Mesh
            activeColor={props.activeColor.color}
            paintMode={props.paintMode}
            modelColors={props.modelColors}
            modelColorsRef={props.modelColorsRef}
            name="pTorus4_tubes_0"
            lightOne={props.lightOne}
            geometry={nodes.pTorus4_tubes_0.geometry}
          />
          <Mesh
            activeColor={props.activeColor.color}
            paintMode={props.paintMode}
            modelColors={props.modelColors}
            modelColorsRef={props.modelColorsRef}
            name="SM_rightEye_mesh1_eyes_0"
            lightOne={props.lightOne}
            geometry={nodes.SM_rightEye_mesh1_eyes_0.geometry}
            decals={props.decalSet}
          />
          <Mesh
            activeColor={props.activeColor.color}
            paintMode={props.paintMode}
            modelColors={props.modelColors}
            modelColorsRef={props.modelColorsRef}
            name="SM_leftEye_mesh1_eyes_0"
            lightOne={props.lightOne}
            geometry={nodes.SM_leftEye_mesh1_eyes_0.geometry}
            decals={props.decalSet}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('spacemarine/sm_helmet/scene.gltf');
