import { makeStyles } from '@material-ui/core/styles';

export const useStyles = makeStyles((theme) => ({
  input: {
    display: 'flex',
    position: 'relative',
    fontFamily: theme.typography.fontFamily,
    resize: 'vertical',
    padding: '10px 0 10px 0',
    marginTop: 3,
    boxShadow: 'inset 3px 3px 10px rgba(0,0,0,0.05)',
    border: 'none',
    borderBottom: `1px dashed ${theme.palette.primary.dark}`,
    background: 'none',
    boxSizing: 'border-box',
    outline: 'none',
    fontSize: 14,
    width: '100%',
    color: theme.palette.primary.main,
  },
  one: {
    display: 'flex',
    flexDirection: 'column',
    marginTop: 3,
    marginBottom: 3,
  },
  two: { width: '100%', display: 'flex', whiteSpace: 'nowrap' },
  descriptionBox: {
    background: theme.palette.primary.dark,
    color: '#fff',
    padding: 10,
    lineHeight: 1,
    textAlign: 'center',
    marginBottom: 20,
    borderRadius: 5,
    width: '100%',
  },
  inputLabel: {
    fontSize: '0.8rem',
    marginTop: 5,
    color: theme.palette.primary.main,
  },
  inputLabelRed: { color: theme.palette.error.main },
  small: {
    display: 'flex',
    width: '100%',
    justifyContent: 'space-between',
  },
  hide: { display: 'none' },
  openClose: {
    width: '100%',
    marginTop: 10,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  socialIcon: {
    width: 30,
    border: '1px solid #ccc',
    borderRadius: '50%',
    marginRight: 10,
  },
  openCloseOff: { display: 'none' },
  infoBox: {
    marginTop: 10,
    background: theme.palette.primary.main,
    color: '#fff',
    padding: 10,
    borderRadius: 5,
  },
  helpIcon: {
    marginLeft: 5,
    cursor: 'pointer',
    color: theme.palette.secondary.main,
    fontSize: 16,
    lineHeight: 1.1,
    '&:hover': {
      color: theme.palette.primary.main,
    },
  },
}));
