const spCol = {
  SM_leftShoulder_shell_Shoulder_shell_0: {
    color: '#2a497f',
    name: 'Calgar Blue',
  },
  Legs_legs_0: { color: '#2a497f', name: 'Calgar Blue' },
  SM_leftThighPlate_mesh2_legs_0: { color: '#2a497f', name: 'Calgar Blue' },
  SM_leftShoe01_mesh_shoes_0: { color: '#2a497f', name: 'Calgar Blue' },
  SM_topHelmet_mesh2_helmet1_0: { color: '#2a497f', name: 'Calgar Blue' },
  SM_leftShoulderShell_mesh23_Shoulder_shell_0: {
    color: '#2a497f',
    name: 'Calgar Blue',
  },
  chest_mesh_chest1_0: { color: '#2a497f', name: 'Calgar Blue' },
  SM_wrist_mesh1_arms_0: { color: '#2a497f', name: 'Calgar Blue' },
  SM_pants_mesh_bodyparts_0: { color: '#2a497f', name: 'Calgar Blue' },
  pCylinder36_hands_0: { color: '#2a497f', name: 'Calgar Blue' },
  default1_bodyparts_0: { color: '#2a497f', name: 'Calgar Blue' },
  pCube17_backpack1_0: { color: '#2a497f', name: 'Calgar Blue' },
  Group7095_backpack1_0: { color: '#2a497f', name: 'Calgar Blue' },
  pSphere4_backpack1_0: { color: '#2a497f', name: 'Calgar Blue' },
  pCube95_flex_0001: { color: '#2a497f', name: 'Calgar Blue' },
  SM_body_mesh_flex_0: { color: '#6a7071', name: 'Ironbreaker' },
  SM_leftHipFlex_mesh_flex_0: { color: '#171314', name: 'Corvus Black' },
  polySurface1_backpack1_0: { color: '#171314', name: 'Corvus Black' },
  SM_rightKnee01_mesh_knees_0: { color: '#2a497f', name: 'Calgar Blue' },
  SM_leftShoulderEdge_mesh9_shoulder_edge_0: {
    color: '#fff',
    name: 'White Scar',
  },
  pPlane13_details_0: { color: '#f5b13d', name: 'auricArmour' },
  SM_wingLeft_mesh_details_0: { color: '#f5b13d', name: 'auricArmour' },
  SM_beltBuckle_mesh_bodyparts_0: { color: '#2a497f', name: 'Calgar Blue' },
  SM_frontHelmet01_mesh1_helmet1_0: { color: '#2a497f', name: 'Calgar Blue' },
  SM_frontHelmet01plate_mesh_mouth_0: { color: '#6a7071', name: 'Ironbreaker' },
  pTorus2_tubes_0: { color: '#6a7071', name: 'Ironbreaker' },
  SM_leftEye_mesh1_eyes_0: { color: '#e82e1b', name: 'Wild Rider Red' },
  SM_bodyWire_mesh1_tubes_0: { color: '#6a7071', name: 'Ironbreaker' },
  SM_armFlex_mesh_flex_0: { color: '#171314', name: 'Corvus Black' },
  SM_chestInner_mesh_chest1_0: { color: '#171314', name: 'Corvus Black' },
};
