export const nameHelper = {
  backpack1: 'Backpack',
  details: 'Aquila',
  bodyparts: 'Pants',
  tubes: 'Tubes',
  flex: 'Flex',
  chest1: 'Chest',
  helmet1: 'Helmet',
  mouth: 'Mouthpiece',
  eyes: 'Lenses',
  knees: 'Kneepad',
  legs: 'Legs',
  shoes: 'Boots',
  arms: 'Arms',
  shoulder_edge: 'Trim',
  Shoulder_shell: 'Paldron',
  hands: 'Hands',
  knee2: 'Left Knee',
  belt: 'Belt',
  obj_0: 'Chassis Central',
  obj_1: 'Hatch R',
  obj_2: 'Hatch L',
  obj_3: 'Turret AC',
  obj_4: 'Turret AC Eject',
  obj_6: 'Turret AC Mount',
  obj_7: 'Turret Main Muzzle',
  obj_8: 'Turret Main Barrel',
  obj_9: 'Turret Hatch Case',
  obj_10: 'Turret Main Casing',
  obj_11: 'Turret Primary',
  obj_12: 'Turret Grenades 1',
  obj_13: 'Turret Main Casing 2',
  obj_14: 'Turret Secondary',
  obj_15: 'Turret MG',
  obj_16: 'Turret Details',
  obj_17: 'Aquila',
  obj_18: 'Turret Grenades 2',
  obj_19: 'Turret Sensor',
  obj_20: 'Turret Comms',
  obj_21: 'Rear Grenades Case',
  obj_22: 'Rear Grenades ',
  obj_23: 'Right Bolter Housing',
  obj_24: 'Front Top Hatch',
  obj_25: 'Right Canister',
  obj_26: 'Right Bolter',
  obj_27: 'Left Bolter',
  obj_28: 'Left Bolter Housing',
  obj_29: 'Right Detail',
  obj_30: 'Left Detail',
  obj_31: 'Left Detail',
  obj_32: 'Right Detail',
  obj_33: 'Right Detail',
  obj_34: 'Left Detail',
  obj_35: 'Left Detail',
  obj_36: 'Hose L',
  obj_37: 'Top Detail',
  obj_38: 'Top Detail',
  obj_39: 'Top Detail',
  obj_40: 'Exhaust L',
  obj_41: 'Top Detail',
  obj_42: 'Front Las',
  obj_43: 'Propulsion',
  obj_44: 'Exhaust R',
  obj_45: 'Hose R',
  obj_46: 'Front Lights',
  obj_47: 'Front Details',
  obj_48: 'Grav Plates',
  obj_49: 'Wires',
  obj_50: 'Marine Body',
  obj_51: 'Marine Tubes',
  obj_52: 'Marine Helmet',
  obj_53: 'Marine Shoulder Inner L',
  obj_54: 'Marine Optics',
  obj_55: 'Marine Optics 2',
  obj_56: 'Marine Elbow L',
  obj_57: 'Marine Wrist L',
  obj_58: 'Marine Arm L',
  obj_59: 'Marine Shoulder L',
  obj_60: 'Marine Elbow R',
  obj_61: 'Marine Wrist R',
  obj_62: 'Marine Hand L',
  obj_63: 'Marine Hand R',
  obj_64: 'Marine Shoulder Inner R',
  obj_65: 'Marine Arm R',
  obj_66: 'Marine Shoulder R',
  obj_67: 'Marine Optics 2',
  obj_68: 'Chassis Outer',
};
