/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react';
import { useGLTF } from '@react-three/drei';
import Mesh from '../Mesh';
export default function Model({ props }) {
  const group = useRef();

  const { nodes } = useGLTF(`${props.gltfIn}`);
  if (!nodes) {
    return 'Loading';
  }
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, -22.65, 0]} scale={20.85}>
        <group position={[0, 1.01, -0.06]} rotation={[0.25, 0, 0]}>
          <group position={[0, 0.15, 0]} rotation={[-0.13, 0, 0]}>
            <group position={[0, 0.14, 0]} rotation={[-0.16, 0, 0]}>
              <group position={[0, 0.17, 0]}>
                <group position={[0, 0.19, 0]} rotation={[0.62, 0, 0]}>
                  <group position={[0, 0.04, 0]} rotation={[-0.46, 0, 0]}>
                    <group position={[0, 0.09, 0]} rotation={[-0.13, 0, 0]}>
                      <Mesh
                        activeColor={props.activeColor}
                        paintMode={props.paintMode}
                        modelColors={props.modelColors}
                        modelColorsRef={props.modelColorsRef}
                        name="VANILLA_BLANK_HELMET_SKULL"
                        lightOne={props.lightOne}
                        geometry={nodes.VANILLA_BLANK_HELMET_SKULL.geometry}
                        position={[0, -0.69, -0.02]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.24, 0.24, 0.24]}
                      />
                      <Mesh
                        activeColor={props.activeColor}
                        paintMode={props.paintMode}
                        modelColors={props.modelColors}
                        modelColorsRef={props.modelColorsRef}
                        name="VANILLA_BLANK_HELMET_SKULL001"
                        lightOne={props.lightOne}
                        geometry={nodes.VANILLA_BLANK_HELMET_SKULL001.geometry}
                        position={[0, -0.69, -0.02]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.24, 0.24, 0.24]}
                      />
                      <Mesh
                        activeColor={props.activeColor}
                        paintMode={props.paintMode}
                        modelColors={props.modelColors}
                        modelColorsRef={props.modelColorsRef}
                        name="VANILLA_BLANK_HELMET_SKULL002"
                        lightOne={props.lightOne}
                        geometry={nodes.VANILLA_BLANK_HELMET_SKULL002.geometry}
                        position={[0, -0.69, -0.02]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.24, 0.24, 0.24]}
                      />
                      <Mesh
                        activeColor={props.activeColor}
                        paintMode={props.paintMode}
                        modelColors={props.modelColors}
                        modelColorsRef={props.modelColorsRef}
                        name="VANILLA_BLANK_HELMET_SKULL003"
                        lightOne={props.lightOne}
                        geometry={nodes.VANILLA_BLANK_HELMET_SKULL003.geometry}
                        position={[0, -0.69, -0.02]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.24, 0.24, 0.24]}
                      />
                      <Mesh
                        activeColor={props.activeColor}
                        paintMode={props.paintMode}
                        modelColors={props.modelColors}
                        modelColorsRef={props.modelColorsRef}
                        name="VANILLA_BLANK_HELMET_SKULL004"
                        lightOne={props.lightOne}
                        geometry={nodes.VANILLA_BLANK_HELMET_SKULL004.geometry}
                        position={[0, -0.69, -0.02]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.24, 0.24, 0.24]}
                      />
                      <Mesh
                        activeColor={props.activeColor}
                        paintMode={props.paintMode}
                        modelColors={props.modelColors}
                        modelColorsRef={props.modelColorsRef}
                        name="VANILLA_BLANK_HELMET_SKULL005"
                        lightOne={props.lightOne}
                        geometry={nodes.VANILLA_BLANK_HELMET_SKULL005.geometry}
                        position={[0, -0.69, -0.02]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.24, 0.24, 0.24]}
                      />
                      <Mesh
                        activeColor={props.activeColor}
                        paintMode={props.paintMode}
                        modelColors={props.modelColors}
                        modelColorsRef={props.modelColorsRef}
                        name="VANILLA_BLANK_HELMET_SKULL006"
                        lightOne={props.lightOne}
                        geometry={nodes.VANILLA_BLANK_HELMET_SKULL006.geometry}
                        position={[0, -0.69, -0.02]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.24, 0.24, 0.24]}
                      />
                      <Mesh
                        activeColor={props.activeColor}
                        paintMode={props.paintMode}
                        modelColors={props.modelColors}
                        modelColorsRef={props.modelColorsRef}
                        name="VANILLA_BLANK_HELMET_SKULL007"
                        lightOne={props.lightOne}
                        geometry={nodes.VANILLA_BLANK_HELMET_SKULL007.geometry}
                        position={[0, -0.69, -0.02]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.24, 0.24, 0.24]}
                      />
                      <Mesh
                        activeColor={props.activeColor}
                        paintMode={props.paintMode}
                        modelColors={props.modelColors}
                        modelColorsRef={props.modelColorsRef}
                        name="VANILLA_BLANK_HELMET_SKULL008"
                        lightOne={props.lightOne}
                        geometry={nodes.VANILLA_BLANK_HELMET_SKULL008.geometry}
                        position={[0, -0.69, -0.02]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.24, 0.24, 0.24]}
                      />
                      <Mesh
                        activeColor={props.activeColor}
                        paintMode={props.paintMode}
                        modelColors={props.modelColors}
                        modelColorsRef={props.modelColorsRef}
                        name="VANILLA_BLANK_HELMET_SKULL009"
                        lightOne={props.lightOne}
                        geometry={nodes.VANILLA_BLANK_HELMET_SKULL009.geometry}
                        position={[0, -0.69, -0.02]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.24, 0.24, 0.24]}
                      />
                      <Mesh
                        activeColor={props.activeColor}
                        paintMode={props.paintMode}
                        modelColors={props.modelColors}
                        modelColorsRef={props.modelColorsRef}
                        name="VANILLA_BLANK_HELMET_SKULL010"
                        lightOne={props.lightOne}
                        geometry={nodes.VANILLA_BLANK_HELMET_SKULL010.geometry}
                        position={[0, -0.69, -0.02]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.24, 0.24, 0.24]}
                      />
                    </group>
                  </group>
                </group>
                <group
                  position={[0.02, 0.14, 0.08]}
                  rotation={[-1.52, 0.01, -1.27]}
                >
                  <group
                    position={[-0.01, 0.32, 0]}
                    rotation={[2.67, 1.42, 2.54]}
                  >
                    <group
                      position={[0, 0.32, 0]}
                      rotation={[0.57, 0.22, -0.21]}
                    >
                      <group
                        position={[0, 0.34, 0]}
                        rotation={[-0.25, -0.08, 0.03]}
                      >
                        <group
                          position={[0, 0.02, 0.02]}
                          rotation={[-2.72, 1.46, 3.05]}
                        >
                          <group
                            position={[0, 0.1, 0]}
                            rotation={[0.18, -0.12, -0.02]}
                          >
                            <group
                              position={[0, 0.06, 0]}
                              rotation={[1.48, -0.2, 0.24]}
                            />
                          </group>
                          <group
                            position={[-0.04, -0.01, 0.03]}
                            rotation={[-1.19, 0.98, 1.6]}
                          >
                            <group
                              position={[0, 0.06, 0]}
                              rotation={[0.4, -0.17, 0.31]}
                            >
                              <group
                                position={[0, 0.04, 0]}
                                rotation={[0.74, -0.1, 0.27]}
                              >
                                <group
                                  position={[-0.58, -0.17, 0.01]}
                                  rotation={[-0.8, -0.01, -0.08]}
                                  scale={[0.24, 0.24, 0.24]}
                                >
                                  <Mesh
                                    activeColor={props.activeColor}
                                    paintMode={props.paintMode}
                                    modelColors={props.modelColors}
                                    modelColorsRef={props.modelColorsRef}
                                    name="L_HAND_THUMB_3_1"
                                    lightOne={props.lightOne}
                                    geometry={nodes.L_HAND_THUMB_3_1.geometry}
                                  />
                                  <Mesh
                                    activeColor={props.activeColor}
                                    paintMode={props.paintMode}
                                    modelColors={props.modelColors}
                                    modelColorsRef={props.modelColorsRef}
                                    name="L_HAND_THUMB_3_2"
                                    lightOne={props.lightOne}
                                    geometry={nodes.L_HAND_THUMB_3_2.geometry}
                                  />
                                  <Mesh
                                    activeColor={props.activeColor}
                                    paintMode={props.paintMode}
                                    modelColors={props.modelColors}
                                    modelColorsRef={props.modelColorsRef}
                                    name="L_HAND_THUMB_3_3"
                                    lightOne={props.lightOne}
                                    geometry={nodes.L_HAND_THUMB_3_3.geometry}
                                  />
                                  <Mesh
                                    activeColor={props.activeColor}
                                    paintMode={props.paintMode}
                                    modelColors={props.modelColors}
                                    modelColorsRef={props.modelColorsRef}
                                    name="L_HAND_THUMB_3_4"
                                    lightOne={props.lightOne}
                                    geometry={nodes.L_HAND_THUMB_3_4.geometry}
                                  />
                                  <Mesh
                                    activeColor={props.activeColor}
                                    paintMode={props.paintMode}
                                    modelColors={props.modelColors}
                                    modelColorsRef={props.modelColorsRef}
                                    name="L_HAND_THUMB_3_5"
                                    lightOne={props.lightOne}
                                    geometry={nodes.L_HAND_THUMB_3_5.geometry}
                                  />
                                  <Mesh
                                    activeColor={props.activeColor}
                                    paintMode={props.paintMode}
                                    modelColors={props.modelColors}
                                    modelColorsRef={props.modelColorsRef}
                                    name="L_HAND_THUMB_3_6"
                                    lightOne={props.lightOne}
                                    geometry={nodes.L_HAND_THUMB_3_6.geometry}
                                  />
                                  <Mesh
                                    activeColor={props.activeColor}
                                    paintMode={props.paintMode}
                                    modelColors={props.modelColors}
                                    modelColorsRef={props.modelColorsRef}
                                    name="L_HAND_THUMB_3_7"
                                    lightOne={props.lightOne}
                                    geometry={nodes.L_HAND_THUMB_3_7.geometry}
                                  />
                                  <Mesh
                                    activeColor={props.activeColor}
                                    paintMode={props.paintMode}
                                    modelColors={props.modelColors}
                                    modelColorsRef={props.modelColorsRef}
                                    name="L_HAND_THUMB_3_8"
                                    lightOne={props.lightOne}
                                    geometry={nodes.L_HAND_THUMB_3_8.geometry}
                                  />
                                  <Mesh
                                    activeColor={props.activeColor}
                                    paintMode={props.paintMode}
                                    modelColors={props.modelColors}
                                    modelColorsRef={props.modelColorsRef}
                                    name="L_HAND_THUMB_3_9"
                                    lightOne={props.lightOne}
                                    geometry={nodes.L_HAND_THUMB_3_9.geometry}
                                  />
                                  <Mesh
                                    activeColor={props.activeColor}
                                    paintMode={props.paintMode}
                                    modelColors={props.modelColors}
                                    modelColorsRef={props.modelColorsRef}
                                    name="L_HAND_THUMB_3_10"
                                    lightOne={props.lightOne}
                                    geometry={nodes.L_HAND_THUMB_3_10.geometry}
                                  />
                                  <Mesh
                                    activeColor={props.activeColor}
                                    paintMode={props.paintMode}
                                    modelColors={props.modelColors}
                                    modelColorsRef={props.modelColorsRef}
                                    name="L_HAND_THUMB_3_11"
                                    lightOne={props.lightOne}
                                    geometry={nodes.L_HAND_THUMB_3_11.geometry}
                                  />
                                  <Mesh
                                    activeColor={props.activeColor}
                                    paintMode={props.paintMode}
                                    modelColors={props.modelColors}
                                    modelColorsRef={props.modelColorsRef}
                                    name="L_HAND_THUMB_3_12"
                                    lightOne={props.lightOne}
                                    geometry={nodes.L_HAND_THUMB_3_12.geometry}
                                  />
                                  <Mesh
                                    activeColor={props.activeColor}
                                    paintMode={props.paintMode}
                                    modelColors={props.modelColors}
                                    modelColorsRef={props.modelColorsRef}
                                    name="L_HAND_THUMB_3_13"
                                    lightOne={props.lightOne}
                                    geometry={nodes.L_HAND_THUMB_3_13.geometry}
                                  />
                                  <Mesh
                                    activeColor={props.activeColor}
                                    paintMode={props.paintMode}
                                    modelColors={props.modelColors}
                                    modelColorsRef={props.modelColorsRef}
                                    name="L_HAND_THUMB_3_14"
                                    lightOne={props.lightOne}
                                    geometry={nodes.L_HAND_THUMB_3_14.geometry}
                                  />
                                  <Mesh
                                    activeColor={props.activeColor}
                                    paintMode={props.paintMode}
                                    modelColors={props.modelColors}
                                    modelColorsRef={props.modelColorsRef}
                                    name="L_HAND_THUMB_3_15"
                                    lightOne={props.lightOne}
                                    geometry={nodes.L_HAND_THUMB_3_15.geometry}
                                  />
                                  <Mesh
                                    activeColor={props.activeColor}
                                    paintMode={props.paintMode}
                                    modelColors={props.modelColors}
                                    modelColorsRef={props.modelColorsRef}
                                    name="L_HAND_THUMB_3_16"
                                    lightOne={props.lightOne}
                                    geometry={nodes.L_HAND_THUMB_3_16.geometry}
                                  />
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                        <group
                          position={[-0.01, 0.02, 0]}
                          rotation={[-2.25, 1.52, 2.41]}
                        >
                          <group
                            position={[0, 0.1, 0]}
                            rotation={[0.28, -0.06, 0]}
                          >
                            <group
                              position={[0, 0.07, 0]}
                              rotation={[1.49, -0.16, 0.22]}
                            />
                          </group>
                        </group>
                        <group
                          position={[0, 0.03, -0.01]}
                          rotation={[-0.11, 1.49, 0.08]}
                        >
                          <group
                            position={[0, 0.09, 0]}
                            rotation={[0.18, -0.01, 0.02]}
                          >
                            <group
                              position={[0, 0.07, 0]}
                              rotation={[1.6, -0.21, 0.02]}
                            />
                          </group>
                        </group>
                        <group
                          position={[0, 0.03, -0.03]}
                          rotation={[0.23, 1.45, -0.53]}
                        >
                          <group
                            position={[0, 0.1, 0]}
                            rotation={[0.41, -0.06, 0.36]}
                          >
                            <group
                              position={[0, 0.05, 0]}
                              rotation={[1.25, -0.36, -0.21]}
                            />
                          </group>
                        </group>
                        <Mesh
                          activeColor={props.activeColor}
                          paintMode={props.paintMode}
                          modelColors={props.modelColors}
                          modelColorsRef={props.modelColorsRef}
                          name="SHIELD_2"
                          lightOne={props.lightOne}
                          geometry={nodes.SHIELD_2.geometry}
                          position={[-0.16, 0.17, -0.13]}
                          rotation={[-1.79, 0.38, -2.69]}
                          scale={[0.24, 0.24, 0.24]}
                        />
                        <Mesh
                          activeColor={props.activeColor}
                          paintMode={props.paintMode}
                          modelColors={props.modelColors}
                          modelColorsRef={props.modelColorsRef}
                          name="SHIELD_2001"
                          lightOne={props.lightOne}
                          geometry={nodes.SHIELD_2001.geometry}
                          position={[-0.16, 0.17, -0.13]}
                          rotation={[-1.79, 0.38, -2.69]}
                          scale={[0.24, 0.24, 0.24]}
                        />
                        <Mesh
                          activeColor={props.activeColor}
                          paintMode={props.paintMode}
                          modelColors={props.modelColors}
                          modelColorsRef={props.modelColorsRef}
                          name="SHIELD_2002"
                          lightOne={props.lightOne}
                          geometry={nodes.SHIELD_2002.geometry}
                          position={[-0.16, 0.17, -0.13]}
                          rotation={[-1.79, 0.38, -2.69]}
                          scale={[0.24, 0.24, 0.24]}
                        />
                        <Mesh
                          activeColor={props.activeColor}
                          paintMode={props.paintMode}
                          modelColors={props.modelColors}
                          modelColorsRef={props.modelColorsRef}
                          name="SHIELD_2003"
                          lightOne={props.lightOne}
                          geometry={nodes.SHIELD_2003.geometry}
                          position={[-0.16, 0.17, -0.13]}
                          rotation={[-1.79, 0.38, -2.69]}
                          scale={[0.24, 0.24, 0.24]}
                        />
                        <Mesh
                          activeColor={props.activeColor}
                          paintMode={props.paintMode}
                          modelColors={props.modelColors}
                          modelColorsRef={props.modelColorsRef}
                          name="SHIELD_2004"
                          lightOne={props.lightOne}
                          geometry={nodes.SHIELD_2004.geometry}
                          position={[-0.16, 0.17, -0.13]}
                          rotation={[-1.79, 0.38, -2.69]}
                          scale={[0.24, 0.24, 0.24]}
                        />
                        <Mesh
                          activeColor={props.activeColor}
                          paintMode={props.paintMode}
                          modelColors={props.modelColors}
                          modelColorsRef={props.modelColorsRef}
                          name="SHIELD_2005"
                          lightOne={props.lightOne}
                          geometry={nodes.SHIELD_2005.geometry}
                          position={[-0.16, 0.17, -0.13]}
                          rotation={[-1.79, 0.38, -2.69]}
                          scale={[0.24, 0.24, 0.24]}
                        />
                        <Mesh
                          activeColor={props.activeColor}
                          paintMode={props.paintMode}
                          modelColors={props.modelColors}
                          modelColorsRef={props.modelColorsRef}
                          name="SHIELD_2006"
                          lightOne={props.lightOne}
                          geometry={nodes.SHIELD_2006.geometry}
                          position={[-0.16, 0.17, -0.13]}
                          rotation={[-1.79, 0.38, -2.69]}
                          scale={[0.24, 0.24, 0.24]}
                        />
                        <Mesh
                          activeColor={props.activeColor}
                          paintMode={props.paintMode}
                          modelColors={props.modelColors}
                          modelColorsRef={props.modelColorsRef}
                          name="SHIELD_2007"
                          lightOne={props.lightOne}
                          geometry={nodes.SHIELD_2007.geometry}
                          position={[-0.16, 0.17, -0.13]}
                          rotation={[-1.79, 0.38, -2.69]}
                          scale={[0.24, 0.24, 0.24]}
                        />
                        <Mesh
                          activeColor={props.activeColor}
                          paintMode={props.paintMode}
                          modelColors={props.modelColors}
                          modelColorsRef={props.modelColorsRef}
                          name="SHIELD_2008"
                          lightOne={props.lightOne}
                          geometry={nodes.SHIELD_2008.geometry}
                          position={[-0.16, 0.17, -0.13]}
                          rotation={[-1.79, 0.38, -2.69]}
                          scale={[0.24, 0.24, 0.24]}
                        />
                        <Mesh
                          activeColor={props.activeColor}
                          paintMode={props.paintMode}
                          modelColors={props.modelColors}
                          modelColorsRef={props.modelColorsRef}
                          name="SHIELD_2009"
                          lightOne={props.lightOne}
                          geometry={nodes.SHIELD_2009.geometry}
                          position={[-0.16, 0.17, -0.13]}
                          rotation={[-1.79, 0.38, -2.69]}
                          scale={[0.24, 0.24, 0.24]}
                        />
                      </group>
                      <Mesh
                        activeColor={props.activeColor}
                        paintMode={props.paintMode}
                        modelColors={props.modelColors}
                        modelColorsRef={props.modelColorsRef}
                        name="L_FOREARM_BLANK"
                        lightOne={props.lightOne}
                        geometry={nodes.L_FOREARM_BLANK.geometry}
                        position={[0.41, -0.03, -0.06]}
                        rotation={[-2.01, 0.37, -2.78]}
                        scale={[0.24, 0.24, 0.24]}
                      />
                    </group>
                    <group position={[0, 0.32, 0]} rotation={[2, -0.45, -3.05]}>
                      <Mesh
                        activeColor={props.activeColor}
                        paintMode={props.paintMode}
                        modelColors={props.modelColors}
                        modelColorsRef={props.modelColorsRef}
                        name="L_ELBOW"
                        lightOne={props.lightOne}
                        geometry={nodes.L_ELBOW.geometry}
                        position={[-0.47, 0, -0.23]}
                        rotation={[-2.92, -0.02, 0.12]}
                        scale={[0.24, 0.24, 0.24]}
                      />
                    </group>
                    <Mesh
                      activeColor={props.activeColor}
                      paintMode={props.paintMode}
                      modelColors={props.modelColors}
                      modelColorsRef={props.modelColorsRef}
                      name="L_SHOULDER"
                      lightOne={props.lightOne}
                      geometry={nodes.L_SHOULDER.geometry}
                      position={[0.52, 0.3, 0.04]}
                      rotation={[-1.39, 0.48, -2.99]}
                      scale={0.24}
                    />
                  </group>
                  <group
                    position={[-0.01, 0.32, 0]}
                    rotation={[0.24, 0.3, -0.06]}
                  >
                    <Mesh
                      activeColor={props.activeColor}
                      paintMode={props.paintMode}
                      modelColors={props.modelColors}
                      modelColorsRef={props.modelColorsRef}
                      name="L_SHOULDER_PAD_BLANK001"
                      lightOne={props.lightOne}
                      geometry={nodes.L_SHOULDER_PAD_BLANK001.geometry}
                      position={[0.1, -0.42, -0.42]}
                      rotation={[2.91, 0.33, -1.26]}
                      scale={[0.24, 0.24, 0.24]}
                    />
                    <Mesh
                      activeColor={props.activeColor}
                      paintMode={props.paintMode}
                      modelColors={props.modelColors}
                      modelColorsRef={props.modelColorsRef}
                      name="L_SHOULDER_PAD_BLANK002"
                      lightOne={props.lightOne}
                      geometry={nodes.L_SHOULDER_PAD_BLANK002.geometry}
                      position={[0.1, -0.42, -0.42]}
                      rotation={[2.91, 0.33, -1.26]}
                      scale={[0.24, 0.24, 0.24]}
                    />
                  </group>
                </group>
                <group
                  position={[-0.02, 0.14, 0.08]}
                  rotation={[-1.52, -0.01, 1.27]}
                >
                  <group
                    position={[0.01, 0.32, 0]}
                    rotation={[2.67, -1.42, -2.54]}
                  >
                    <group
                      position={[0, 0.32, 0]}
                      rotation={[0.57, -0.22, 0.21]}
                    >
                      <group
                        position={[0, 0.34, 0]}
                        rotation={[-0.25, 0.08, -0.03]}
                      >
                        <group
                          position={[0, 0.02, 0.02]}
                          rotation={[-2.79, -1.46, -3.13]}
                        >
                          <group
                            position={[0, 0.1, 0]}
                            rotation={[-0.02, 0.04, 0.06]}
                          >
                            <group
                              position={[0, 0.06, 0]}
                              rotation={[1.03, 0.2, -0.08]}
                            >
                              <group
                                position={[0, 0.05, 0]}
                                rotation={[1.04, 0.16, -0.28]}
                              >
                                <Mesh
                                  activeColor={props.activeColor}
                                  paintMode={props.paintMode}
                                  modelColors={props.modelColors}
                                  modelColorsRef={props.modelColorsRef}
                                  name="R_HAND_INDEX_3"
                                  lightOne={props.lightOne}
                                  geometry={nodes.R_HAND_INDEX_3.geometry}
                                  position={[0.03, -0.35, 0.58]}
                                  rotation={[-1.44, -0.23, -1.5]}
                                  scale={[0.24, 0.24, 0.24]}
                                />
                              </group>
                              <Mesh
                                activeColor={props.activeColor}
                                paintMode={props.paintMode}
                                modelColors={props.modelColors}
                                modelColorsRef={props.modelColorsRef}
                                name="R_HAND_INDEX_2"
                                lightOne={props.lightOne}
                                geometry={nodes.R_HAND_INDEX_2.geometry}
                                position={[0.06, -0.27, 0.59]}
                                rotation={[-1.47, -0.14, -1.41]}
                                scale={[0.24, 0.24, 0.24]}
                              />
                            </group>
                            <Mesh
                              activeColor={props.activeColor}
                              paintMode={props.paintMode}
                              modelColors={props.modelColors}
                              modelColorsRef={props.modelColorsRef}
                              name="R_HAND_INDEX_1"
                              lightOne={props.lightOne}
                              geometry={nodes.R_HAND_INDEX_1.geometry}
                              position={[0.12, -0.34, 0.51]}
                              rotation={[-1.21, -0.27, -1.35]}
                              scale={[0.24, 0.24, 0.24]}
                            />
                          </group>
                          <group
                            position={[0.04, -0.01, 0.03]}
                            rotation={[-1.14, -1.09, -1.64]}
                          >
                            <group
                              position={[0, 0.06, 0]}
                              rotation={[0.52, -0.01, 0.11]}
                            >
                              <group
                                position={[0, 0.04, 0]}
                                rotation={[0.39, -0.05, -0.2]}
                              >
                                <Mesh
                                  activeColor={props.activeColor}
                                  paintMode={props.paintMode}
                                  modelColors={props.modelColors}
                                  modelColorsRef={props.modelColorsRef}
                                  name="R_HAND_THUMB_3"
                                  lightOne={props.lightOne}
                                  geometry={nodes.R_HAND_THUMB_3.geometry}
                                  position={[0.49, -0.2, -0.14]}
                                  rotation={[-1.19, 0.18, 0.31]}
                                  scale={[0.24, 0.24, 0.24]}
                                />
                              </group>
                              <Mesh
                                activeColor={props.activeColor}
                                paintMode={props.paintMode}
                                modelColors={props.modelColors}
                                modelColorsRef={props.modelColorsRef}
                                name="R_HAND_THUMB_2"
                                lightOne={props.lightOne}
                                geometry={nodes.R_HAND_THUMB_2.geometry}
                                position={[0.48, -0.19, -0.14]}
                                rotation={[-1.23, 0.23, 0.31]}
                                scale={[0.24, 0.24, 0.24]}
                              />
                            </group>
                            <Mesh
                              activeColor={props.activeColor}
                              paintMode={props.paintMode}
                              modelColors={props.modelColors}
                              modelColorsRef={props.modelColorsRef}
                              name="R_HAND_THUMB_1"
                              lightOne={props.lightOne}
                              geometry={nodes.R_HAND_THUMB_1.geometry}
                              position={[0.47, -0.05, -0.23]}
                              rotation={[-0.77, 0.28, 0.33]}
                              scale={[0.24, 0.24, 0.24]}
                            />
                          </group>
                        </group>
                        <group
                          position={[0.01, 0.02, 0]}
                          rotation={[-2.36, -1.52, -2.51]}
                        >
                          <group
                            position={[0, 0.1, 0]}
                            rotation={[0.12, 0.03, 0.02]}
                          >
                            <group
                              position={[0, 0.07, 0]}
                              rotation={[1.14, 0.17, -0.15]}
                            >
                              <group
                                position={[0, 0.05, 0]}
                                rotation={[1.03, 0.18, -0.15]}
                              >
                                <Mesh
                                  activeColor={props.activeColor}
                                  paintMode={props.paintMode}
                                  modelColors={props.modelColors}
                                  modelColorsRef={props.modelColorsRef}
                                  name="R_HAND_MIDDLE_3"
                                  lightOne={props.lightOne}
                                  geometry={nodes.R_HAND_MIDDLE_3.geometry}
                                  position={[0, -0.32, 0.6]}
                                  rotation={[-1.51, -0.21, -1.6]}
                                  scale={[0.24, 0.24, 0.24]}
                                />
                              </group>
                              <Mesh
                                activeColor={props.activeColor}
                                paintMode={props.paintMode}
                                modelColors={props.modelColors}
                                modelColorsRef={props.modelColorsRef}
                                name="R_HAND_MIDDLE_2"
                                lightOne={props.lightOne}
                                geometry={nodes.R_HAND_MIDDLE_2.geometry}
                                position={[0.02, -0.24, 0.62]}
                                rotation={[-1.55, -0.15, -1.55]}
                                scale={[0.24, 0.24, 0.24]}
                              />
                            </group>
                            <Mesh
                              activeColor={props.activeColor}
                              paintMode={props.paintMode}
                              modelColors={props.modelColors}
                              modelColorsRef={props.modelColorsRef}
                              name="R_HAND_MIDDLE_1"
                              lightOne={props.lightOne}
                              geometry={nodes.R_HAND_MIDDLE_1.geometry}
                              position={[0.08, -0.31, 0.54]}
                              rotation={[-1.3, -0.14, -1.44]}
                              scale={[0.24, 0.24, 0.24]}
                            />
                          </group>
                        </group>
                        <group
                          position={[0, 0.03, -0.01]}
                          rotation={[0, -1.49, 0.04]}
                        >
                          <group
                            position={[0, 0.09, 0]}
                            rotation={[0.03, 0.01, -0.02]}
                          >
                            <group
                              position={[0, 0.07, 0]}
                              rotation={[1.22, 0.2, -0.01]}
                            >
                              <group
                                position={[0, 0.05, 0]}
                                rotation={[1.08, 0.3, 0.1]}
                              >
                                <Mesh
                                  activeColor={props.activeColor}
                                  paintMode={props.paintMode}
                                  modelColors={props.modelColors}
                                  modelColorsRef={props.modelColorsRef}
                                  name="R_HAND_RING_3"
                                  lightOne={props.lightOne}
                                  geometry={nodes.R_HAND_RING_3.geometry}
                                  position={[-0.18, -0.25, 0.61]}
                                  rotation={[-1.65, -0.07, -1.91]}
                                  scale={[0.24, 0.24, 0.24]}
                                />
                              </group>
                              <Mesh
                                activeColor={props.activeColor}
                                paintMode={props.paintMode}
                                modelColors={props.modelColors}
                                modelColorsRef={props.modelColorsRef}
                                name="R_HAND_RING_2"
                                lightOne={props.lightOne}
                                geometry={nodes.R_HAND_RING_2.geometry}
                                position={[-0.09, -0.22, 0.62]}
                                rotation={[-1.6, -0.05, -1.75]}
                                scale={[0.24, 0.24, 0.24]}
                              />
                            </group>
                            <Mesh
                              activeColor={props.activeColor}
                              paintMode={props.paintMode}
                              modelColors={props.modelColors}
                              modelColorsRef={props.modelColorsRef}
                              name="R_HAND_RING_1"
                              lightOne={props.lightOne}
                              geometry={nodes.R_HAND_RING_1.geometry}
                              position={[0.01, -0.36, 0.51]}
                              rotation={[-1.23, -0.04, -1.59]}
                              scale={[0.24, 0.24, 0.24]}
                            />
                          </group>
                        </group>
                        <group
                          position={[0, 0.03, -0.03]}
                          rotation={[0.3, -1.44, 0.6]}
                        >
                          <group
                            position={[0, 0.1, 0]}
                            rotation={[0.27, 0.09, -0.39]}
                          >
                            <group
                              position={[0, 0.05, 0]}
                              rotation={[1.19, 0.35, 0.21]}
                            >
                              <group
                                position={[0, 0.05, 0]}
                                rotation={[1.06, 0.26, 0.23]}
                              >
                                <Mesh
                                  activeColor={props.activeColor}
                                  paintMode={props.paintMode}
                                  modelColors={props.modelColors}
                                  modelColorsRef={props.modelColorsRef}
                                  name="R_HAND_PINKY_3"
                                  lightOne={props.lightOne}
                                  geometry={nodes.R_HAND_PINKY_3.geometry}
                                  position={[-0.14, -0.27, 0.59]}
                                  rotation={[-1.6, -0.03, -1.9]}
                                  scale={[0.24, 0.24, 0.24]}
                                />
                              </group>
                              <Mesh
                                activeColor={props.activeColor}
                                paintMode={props.paintMode}
                                modelColors={props.modelColors}
                                modelColorsRef={props.modelColorsRef}
                                name="R_HAND_PINKY_2"
                                lightOne={props.lightOne}
                                geometry={nodes.R_HAND_PINKY_2.geometry}
                                position={[-0.09, -0.25, 0.59]}
                                rotation={[-1.55, -0.06, -1.84]}
                                scale={[0.24, 0.24, 0.24]}
                              />
                            </group>
                            <Mesh
                              activeColor={props.activeColor}
                              paintMode={props.paintMode}
                              modelColors={props.modelColors}
                              modelColorsRef={props.modelColorsRef}
                              name="R_HAND_PINKY_1"
                              lightOne={props.lightOne}
                              geometry={nodes.R_HAND_PINKY_1.geometry}
                              position={[-0.03, -0.24, 0.57]}
                              rotation={[-1.48, -0.18, -1.77]}
                              scale={[0.24, 0.24, 0.24]}
                            />
                          </group>
                        </group>
                        <Mesh
                          activeColor={props.activeColor}
                          paintMode={props.paintMode}
                          modelColors={props.modelColors}
                          modelColorsRef={props.modelColorsRef}
                          name="R_HAND_PALM_ARMOR"
                          lightOne={props.lightOne}
                          geometry={nodes.R_HAND_PALM_ARMOR.geometry}
                          position={[-0.49, -0.26, 0.05]}
                          rotation={[-1.6, -0.37, -3.08]}
                          scale={[0.24, 0.24, 0.24]}
                        />
                        <Mesh
                          activeColor={props.activeColor}
                          paintMode={props.paintMode}
                          modelColors={props.modelColors}
                          modelColorsRef={props.modelColorsRef}
                          name="SWORD"
                          lightOne={props.lightOne}
                          geometry={nodes.SWORD.geometry}
                          position={[-0.04, 0.14, 0.11]}
                          rotation={[-1.6, -0.37, -3.08]}
                          scale={[0.24, 0.24, 0.24]}
                        />
                        <Mesh
                          activeColor={props.activeColor}
                          paintMode={props.paintMode}
                          modelColors={props.modelColors}
                          modelColorsRef={props.modelColorsRef}
                          name="SWORD001"
                          lightOne={props.lightOne}
                          geometry={nodes.SWORD001.geometry}
                          position={[-0.04, 0.14, 0.11]}
                          rotation={[-1.6, -0.37, -3.08]}
                          scale={[0.24, 0.24, 0.24]}
                        />
                        <Mesh
                          activeColor={props.activeColor}
                          paintMode={props.paintMode}
                          modelColors={props.modelColors}
                          modelColorsRef={props.modelColorsRef}
                          name="SWORD002"
                          lightOne={props.lightOne}
                          geometry={nodes.SWORD002.geometry}
                          position={[-0.04, 0.14, 0.11]}
                          rotation={[-1.6, -0.37, -3.08]}
                          scale={[0.24, 0.24, 0.24]}
                        />
                        <Mesh
                          activeColor={props.activeColor}
                          paintMode={props.paintMode}
                          modelColors={props.modelColors}
                          modelColorsRef={props.modelColorsRef}
                          name="SWORD003"
                          lightOne={props.lightOne}
                          geometry={nodes.SWORD003.geometry}
                          position={[-0.04, 0.14, 0.11]}
                          rotation={[-1.6, -0.37, -3.08]}
                          scale={[0.24, 0.24, 0.24]}
                        />
                        <Mesh
                          activeColor={props.activeColor}
                          paintMode={props.paintMode}
                          modelColors={props.modelColors}
                          modelColorsRef={props.modelColorsRef}
                          name="SWORD004"
                          lightOne={props.lightOne}
                          geometry={nodes.SWORD004.geometry}
                          position={[-0.04, 0.14, 0.11]}
                          rotation={[-1.6, -0.37, -3.08]}
                          scale={[0.24, 0.24, 0.24]}
                        />
                      </group>
                      <Mesh
                        activeColor={props.activeColor}
                        paintMode={props.paintMode}
                        modelColors={props.modelColors}
                        modelColorsRef={props.modelColorsRef}
                        name="R_FOREARM_BLANK"
                        lightOne={props.lightOne}
                        geometry={nodes.R_FOREARM_BLANK.geometry}
                        position={[-0.49, 0.11, 0.15]}
                        rotation={[-1.82, -0.35, -3]}
                        scale={[0.24, 0.24, 0.24]}
                      />
                    </group>
                    <group position={[0, 0.32, 0]} rotation={[2, 0.45, 3.05]}>
                      <Mesh
                        activeColor={props.activeColor}
                        paintMode={props.paintMode}
                        modelColors={props.modelColors}
                        modelColorsRef={props.modelColorsRef}
                        name="R_ELBOW"
                        lightOne={props.lightOne}
                        geometry={nodes.R_ELBOW.geometry}
                        position={[0.47, 0, -0.23]}
                        rotation={[-2.92, 0.02, -0.12]}
                        scale={[0.24, 0.24, 0.24]}
                      />
                    </group>
                    <Mesh
                      activeColor={props.activeColor}
                      paintMode={props.paintMode}
                      modelColors={props.modelColors}
                      modelColorsRef={props.modelColorsRef}
                      name="R_SHOULDER"
                      lightOne={props.lightOne}
                      geometry={nodes.R_SHOULDER.geometry}
                      position={[-0.52, 0.3, 0.04]}
                      rotation={[-1.39, -0.48, 2.99]}
                      scale={0.24}
                    />
                  </group>
                  <group
                    position={[0.01, 0.32, 0]}
                    rotation={[0.24, -0.3, 0.06]}
                  >
                    <Mesh
                      activeColor={props.activeColor}
                      paintMode={props.paintMode}
                      modelColors={props.modelColors}
                      modelColorsRef={props.modelColorsRef}
                      name="R_SHOULDER_PAD_BLANK"
                      lightOne={props.lightOne}
                      geometry={nodes.R_SHOULDER_PAD_BLANK.geometry}
                      position={[-0.1, -0.42, -0.42]}
                      rotation={[2.91, -0.33, 1.26]}
                      scale={[0.24, 0.24, 0.24]}
                    />
                    <Mesh
                      activeColor={props.activeColor}
                      paintMode={props.paintMode}
                      modelColors={props.modelColors}
                      modelColorsRef={props.modelColorsRef}
                      name="R_SHOULDER_PAD_BLANK001"
                      lightOne={props.lightOne}
                      geometry={nodes.R_SHOULDER_PAD_BLANK001.geometry}
                      position={[-0.1, -0.42, -0.42]}
                      rotation={[2.91, -0.33, 1.26]}
                      scale={[0.24, 0.24, 0.24]}
                    />
                  </group>
                </group>
                <Mesh
                  activeColor={props.activeColor}
                  paintMode={props.paintMode}
                  modelColors={props.modelColors}
                  modelColorsRef={props.modelColorsRef}
                  name="BP_BACK_VENTS"
                  lightOne={props.lightOne}
                  geometry={nodes.BP_BACK_VENTS.geometry}
                  position={[0, -0.38, 0]}
                  rotation={[1.6, 0, 0]}
                  scale={0.24}
                />
                <Mesh
                  activeColor={props.activeColor}
                  paintMode={props.paintMode}
                  modelColors={props.modelColors}
                  modelColorsRef={props.modelColorsRef}
                  name="BP_BOTTOM_VENT"
                  lightOne={props.lightOne}
                  geometry={nodes.BP_BOTTOM_VENT.geometry}
                  position={[0, -0.38, 0]}
                  rotation={[1.6, 0, 0]}
                  scale={0.24}
                />
                <Mesh
                  activeColor={props.activeColor}
                  paintMode={props.paintMode}
                  modelColors={props.modelColors}
                  modelColorsRef={props.modelColorsRef}
                  name="BP_BRACKETS"
                  lightOne={props.lightOne}
                  geometry={nodes.BP_BRACKETS.geometry}
                  position={[0, -0.38, 0]}
                  rotation={[1.6, 0, 0]}
                  scale={0.24}
                />
                <Mesh
                  activeColor={props.activeColor}
                  paintMode={props.paintMode}
                  modelColors={props.modelColors}
                  modelColorsRef={props.modelColorsRef}
                  name="BP_EXHAUST"
                  lightOne={props.lightOne}
                  geometry={nodes.BP_EXHAUST.geometry}
                  position={[0, -0.38, 0]}
                  rotation={[1.6, 0, 0]}
                  scale={0.24}
                />
                <Mesh
                  activeColor={props.activeColor}
                  paintMode={props.paintMode}
                  modelColors={props.modelColors}
                  modelColorsRef={props.modelColorsRef}
                  name="BP_HALO"
                  lightOne={props.lightOne}
                  geometry={nodes.BP_HALO.geometry}
                  position={[0, -0.38, 0]}
                  rotation={[1.6, 0, 0]}
                  scale={0.24}
                />
                <Mesh
                  activeColor={props.activeColor}
                  paintMode={props.paintMode}
                  modelColors={props.modelColors}
                  modelColorsRef={props.modelColorsRef}
                  name="BP_INDENT"
                  lightOne={props.lightOne}
                  geometry={nodes.BP_INDENT.geometry}
                  position={[0, -0.38, 0]}
                  rotation={[1.6, 0, 0]}
                  scale={0.24}
                />
                <Mesh
                  activeColor={props.activeColor}
                  paintMode={props.paintMode}
                  modelColors={props.modelColors}
                  modelColorsRef={props.modelColorsRef}
                  name="BP_INDENT_FRONT"
                  lightOne={props.lightOne}
                  geometry={nodes.BP_INDENT_FRONT.geometry}
                  position={[0, -0.38, 0]}
                  rotation={[1.6, 0, 0]}
                  scale={0.24}
                />
                <Mesh
                  activeColor={props.activeColor}
                  paintMode={props.paintMode}
                  modelColors={props.modelColors}
                  modelColorsRef={props.modelColorsRef}
                  name="BP_JOINT"
                  lightOne={props.lightOne}
                  geometry={nodes.BP_JOINT.geometry}
                  position={[0, -0.38, 0]}
                  rotation={[1.6, 0, 0]}
                  scale={0.24}
                />
                <Mesh
                  activeColor={props.activeColor}
                  paintMode={props.paintMode}
                  modelColors={props.modelColors}
                  modelColorsRef={props.modelColorsRef}
                  name="BP_MAIN"
                  lightOne={props.lightOne}
                  geometry={nodes.BP_MAIN.geometry}
                  position={[0, -0.38, 0]}
                  rotation={[1.6, 0, 0]}
                  scale={0.24}
                />
                <Mesh
                  activeColor={props.activeColor}
                  paintMode={props.paintMode}
                  modelColors={props.modelColors}
                  modelColorsRef={props.modelColorsRef}
                  name="BP_PLATE"
                  lightOne={props.lightOne}
                  geometry={nodes.BP_PLATE.geometry}
                  position={[0, -0.38, 0]}
                  rotation={[1.6, 0, 0]}
                  scale={0.24}
                />
                <Mesh
                  activeColor={props.activeColor}
                  paintMode={props.paintMode}
                  modelColors={props.modelColors}
                  modelColorsRef={props.modelColorsRef}
                  name="BP_SKULL"
                  lightOne={props.lightOne}
                  geometry={nodes.BP_SKULL.geometry}
                  position={[0, -0.38, 0]}
                  rotation={[1.6, 0, 0]}
                  scale={0.24}
                />
                <Mesh
                  activeColor={props.activeColor}
                  paintMode={props.paintMode}
                  modelColors={props.modelColors}
                  modelColorsRef={props.modelColorsRef}
                  name="BP_STUDS"
                  lightOne={props.lightOne}
                  geometry={nodes.BP_STUDS.geometry}
                  position={[0, -0.38, 0]}
                  rotation={[1.6, 0, 0]}
                  scale={0.24}
                />
                <Mesh
                  activeColor={props.activeColor}
                  paintMode={props.paintMode}
                  modelColors={props.modelColors}
                  modelColorsRef={props.modelColorsRef}
                  name="BP_TECH"
                  lightOne={props.lightOne}
                  geometry={nodes.BP_TECH.geometry}
                  position={[0, -0.38, 0]}
                  rotation={[1.6, 0, 0]}
                  scale={0.24}
                />
                <Mesh
                  activeColor={props.activeColor}
                  paintMode={props.paintMode}
                  modelColors={props.modelColors}
                  modelColorsRef={props.modelColorsRef}
                  name="BP_TOP_SKULL"
                  lightOne={props.lightOne}
                  geometry={nodes.BP_TOP_SKULL.geometry}
                  position={[0, -0.38, 0]}
                  rotation={[1.6, 0, 0]}
                  scale={0.24}
                />
                <Mesh
                  activeColor={props.activeColor}
                  paintMode={props.paintMode}
                  modelColors={props.modelColors}
                  modelColorsRef={props.modelColorsRef}
                  name="BP_VENT"
                  lightOne={props.lightOne}
                  geometry={nodes.BP_VENT.geometry}
                  position={[0, -0.38, 0]}
                  rotation={[1.6, 0, 0]}
                  scale={0.24}
                />
                <Mesh
                  activeColor={props.activeColor}
                  paintMode={props.paintMode}
                  modelColors={props.modelColors}
                  modelColorsRef={props.modelColorsRef}
                  name="CHEST_WINGED"
                  lightOne={props.lightOne}
                  geometry={nodes.CHEST_WINGED.geometry}
                  position={[0, -0.38, 0]}
                  rotation={[1.6, 0, 0]}
                  scale={0.24}
                />
                <Mesh
                  activeColor={props.activeColor}
                  paintMode={props.paintMode}
                  modelColors={props.modelColors}
                  modelColorsRef={props.modelColorsRef}
                  name="CHEST_WINGED001"
                  lightOne={props.lightOne}
                  geometry={nodes.CHEST_WINGED001.geometry}
                  position={[0, -0.38, 0]}
                  rotation={[1.6, 0, 0]}
                  scale={0.24}
                />
                <Mesh
                  activeColor={props.activeColor}
                  paintMode={props.paintMode}
                  modelColors={props.modelColors}
                  modelColorsRef={props.modelColorsRef}
                  name="CHEST_WINGED002"
                  lightOne={props.lightOne}
                  geometry={nodes.CHEST_WINGED002.geometry}
                  position={[0, -0.38, 0]}
                  rotation={[1.6, 0, 0]}
                  scale={0.24}
                />
                <Mesh
                  activeColor={props.activeColor}
                  paintMode={props.paintMode}
                  modelColors={props.modelColors}
                  modelColorsRef={props.modelColorsRef}
                  name="CHEST_WINGED003"
                  lightOne={props.lightOne}
                  geometry={nodes.CHEST_WINGED003.geometry}
                  position={[0, -0.38, 0]}
                  rotation={[1.6, 0, 0]}
                  scale={0.24}
                />
                <Mesh
                  activeColor={props.activeColor}
                  paintMode={props.paintMode}
                  modelColors={props.modelColors}
                  modelColorsRef={props.modelColorsRef}
                  name="CHEST_WINGED004"
                  lightOne={props.lightOne}
                  geometry={nodes.CHEST_WINGED004.geometry}
                  position={[0, -0.38, 0]}
                  rotation={[1.6, 0, 0]}
                  scale={0.24}
                />
                <Mesh
                  activeColor={props.activeColor}
                  paintMode={props.paintMode}
                  modelColors={props.modelColors}
                  modelColorsRef={props.modelColorsRef}
                  name="CHEST_WINGED005"
                  lightOne={props.lightOne}
                  geometry={nodes.CHEST_WINGED005.geometry}
                  position={[0, -0.38, 0]}
                  rotation={[1.6, 0, 0]}
                  scale={0.24}
                />
                <Mesh
                  activeColor={props.activeColor}
                  paintMode={props.paintMode}
                  modelColors={props.modelColors}
                  modelColorsRef={props.modelColorsRef}
                  name="TORSO_SHIELD_A"
                  lightOne={props.lightOne}
                  geometry={nodes.TORSO_SHIELD_A.geometry}
                  position={[0, -0.38, 0]}
                  rotation={[1.6, 0, 0]}
                  scale={0.24}
                />
                <Mesh
                  activeColor={props.activeColor}
                  paintMode={props.paintMode}
                  modelColors={props.modelColors}
                  modelColorsRef={props.modelColorsRef}
                  name="TORSO_SHIELD_A001"
                  lightOne={props.lightOne}
                  geometry={nodes.TORSO_SHIELD_A001.geometry}
                  position={[0, -0.38, 0]}
                  rotation={[1.6, 0, 0]}
                  scale={0.24}
                />
                <Mesh
                  activeColor={props.activeColor}
                  paintMode={props.paintMode}
                  modelColors={props.modelColors}
                  modelColorsRef={props.modelColorsRef}
                  name="TORSO_SHIELD_A002"
                  lightOne={props.lightOne}
                  geometry={nodes.TORSO_SHIELD_A002.geometry}
                  position={[0, -0.38, 0]}
                  rotation={[1.6, 0, 0]}
                  scale={0.24}
                />
                <Mesh
                  activeColor={props.activeColor}
                  paintMode={props.paintMode}
                  modelColors={props.modelColors}
                  modelColorsRef={props.modelColorsRef}
                  name="TORSO_SHIELD_A003"
                  lightOne={props.lightOne}
                  geometry={nodes.TORSO_SHIELD_A003.geometry}
                  position={[0, -0.38, 0]}
                  rotation={[1.6, 0, 0]}
                  scale={0.24}
                />
                <Mesh
                  activeColor={props.activeColor}
                  paintMode={props.paintMode}
                  modelColors={props.modelColors}
                  modelColorsRef={props.modelColorsRef}
                  name="TORSO_SHIELD_A004"
                  lightOne={props.lightOne}
                  geometry={nodes.TORSO_SHIELD_A004.geometry}
                  position={[0, -0.38, 0]}
                  rotation={[1.6, 0, 0]}
                  scale={0.24}
                />
              </group>
            </group>
            <Mesh
              activeColor={props.activeColor}
              paintMode={props.paintMode}
              modelColors={props.modelColors}
              modelColorsRef={props.modelColorsRef}
              name="LOWER_TORSO"
              lightOne={props.lightOne}
              geometry={nodes.LOWER_TORSO.geometry}
              position={[0, -0.07, 0.03]}
              rotation={[1.45, 0, 0]}
              scale={[0.24, 0.24, 0.24]}
            />
          </group>
          <group rotation={[-1.74, -0.4, -2.03]}>
            <group position={[0, 0.21, 0]} rotation={[-0.12, 0.15, 0.68]}>
              <Mesh
                activeColor={props.activeColor}
                paintMode={props.paintMode}
                modelColors={props.modelColors}
                modelColorsRef={props.modelColorsRef}
                name="L_BLANK_HIP_ARMOR"
                lightOne={props.lightOne}
                geometry={nodes.L_BLANK_HIP_ARMOR.geometry}
                position={[-0.09, -0.14, 0.06]}
                rotation={[2.72, 0.18, -1.3]}
                scale={[0.24, 0.24, 0.24]}
              />
              <Mesh
                activeColor={props.activeColor}
                paintMode={props.paintMode}
                modelColors={props.modelColors}
                modelColorsRef={props.modelColorsRef}
                name="L_BLANK_HIP_ARMOR001"
                lightOne={props.lightOne}
                geometry={nodes.L_BLANK_HIP_ARMOR001.geometry}
                position={[-0.09, -0.14, 0.06]}
                rotation={[2.72, 0.18, -1.3]}
                scale={[0.24, 0.24, 0.24]}
              />
              <Mesh
                activeColor={props.activeColor}
                paintMode={props.paintMode}
                modelColors={props.modelColors}
                modelColorsRef={props.modelColorsRef}
                name="L_BLANK_HIP_ARMOR002"
                lightOne={props.lightOne}
                geometry={nodes.L_BLANK_HIP_ARMOR002.geometry}
                position={[-0.09, -0.14, 0.06]}
                rotation={[2.72, 0.18, -1.3]}
                scale={[0.24, 0.24, 0.24]}
              />
            </group>
          </group>
          <group rotation={[-1.74, 0.4, 2.03]}>
            <group position={[0, 0.21, 0]} rotation={[-0.12, -0.15, -0.68]}>
              <Mesh
                activeColor={props.activeColor}
                paintMode={props.paintMode}
                modelColors={props.modelColors}
                modelColorsRef={props.modelColorsRef}
                name="R_AQUILA_HIP_ARMOR"
                lightOne={props.lightOne}
                geometry={nodes.R_AQUILA_HIP_ARMOR.geometry}
                position={[0.09, -0.14, 0.06]}
                rotation={[2.72, -0.18, 1.3]}
                scale={[0.24, 0.24, 0.24]}
              />
              <Mesh
                activeColor={props.activeColor}
                paintMode={props.paintMode}
                modelColors={props.modelColors}
                modelColorsRef={props.modelColorsRef}
                name="R_AQUILA_HIP_ARMOR001"
                lightOne={props.lightOne}
                geometry={nodes.R_AQUILA_HIP_ARMOR001.geometry}
                position={[0.09, -0.14, 0.06]}
                rotation={[2.72, -0.18, 1.3]}
                scale={[0.24, 0.24, 0.24]}
              />
            </group>
          </group>
          <group position={[0.19, 0.05, 0.03]} rotation={[2.8, 0, -0.27]}>
            <group position={[0, 0.43, 0]} rotation={[0.24, 0.05, 0.07]}>
              <group position={[0, 0.49, 0]} rotation={[-1.12, -0.17, -0.03]} />
              <group position={[0, 0.49, 0]} rotation={[-2.4, -1.32, -0.57]}>
                <Mesh
                  activeColor={props.activeColor}
                  paintMode={props.paintMode}
                  modelColors={props.modelColors}
                  modelColorsRef={props.modelColorsRef}
                  name="L_FOOT_TOP_PLATE"
                  lightOne={props.lightOne}
                  geometry={nodes.L_FOOT_TOP_PLATE.geometry}
                  position={[-1, 0.14, 0.02]}
                  rotation={[0.33, 1.16, -0.22]}
                  scale={[0.24, 0.24, 0.24]}
                />
              </group>
              <Mesh
                activeColor={props.activeColor}
                paintMode={props.paintMode}
                modelColors={props.modelColors}
                modelColorsRef={props.modelColorsRef}
                name="L_SHIN_A"
                lightOne={props.lightOne}
                geometry={nodes.L_SHIN_A.geometry}
                position={[-0.21, -0.49, 0.1]}
                rotation={[-1.74, -0.19, -0.02]}
                scale={[0.24, 0.24, 0.24]}
              />
            </group>
            <group position={[0, 0.43, 0]} rotation={[0.34, -0.3, -1.45]}>
              <Mesh
                activeColor={props.activeColor}
                paintMode={props.paintMode}
                modelColors={props.modelColors}
                modelColorsRef={props.modelColorsRef}
                name="L_LEG_ARMOR"
                lightOne={props.lightOne}
                geometry={nodes.L_LEG_ARMOR.geometry}
                position={[0.47, -0.18, 0.2]}
                rotation={[2.2, -1.31, -2.14]}
                scale={[0.24, 0.24, 0.24]}
              />
            </group>
            <Mesh
              activeColor={props.activeColor}
              paintMode={props.paintMode}
              modelColors={props.modelColors}
              modelColorsRef={props.modelColorsRef}
              name="L_THIGH"
              lightOne={props.lightOne}
              geometry={nodes.L_THIGH.geometry}
              position={[-0.18, -0.07, -0.01]}
              rotation={[-1.48, -0.27, 0.02]}
              scale={[0.24, 0.24, 0.24]}
            />
          </group>
          <group position={[-0.19, 0.05, 0.03]} rotation={[2.8, 0, 0.27]}>
            <group position={[0, 0.43, 0]} rotation={[0.24, -0.05, -0.07]}>
              <group position={[0, 0.49, 0]} rotation={[-1.12, 0.17, 0.03]} />
              <group position={[0, 0.49, 0]} rotation={[-2.4, 1.32, 0.57]}>
                <Mesh
                  activeColor={props.activeColor}
                  paintMode={props.paintMode}
                  modelColors={props.modelColors}
                  modelColorsRef={props.modelColorsRef}
                  name="R_FOOT_TOP_PLATE"
                  lightOne={props.lightOne}
                  geometry={nodes.R_FOOT_TOP_PLATE.geometry}
                  position={[1, 0.14, 0.02]}
                  rotation={[0.33, -1.16, 0.22]}
                  scale={[0.24, 0.24, 0.24]}
                />
              </group>
              <Mesh
                activeColor={props.activeColor}
                paintMode={props.paintMode}
                modelColors={props.modelColors}
                modelColorsRef={props.modelColorsRef}
                name="R_SHIN_A"
                lightOne={props.lightOne}
                geometry={nodes.R_SHIN_A.geometry}
                position={[0.21, -0.49, 0.1]}
                rotation={[-1.74, 0.19, 0.02]}
                scale={[0.24, 0.24, 0.24]}
              />
            </group>
            <group position={[0, 0.43, 0]} rotation={[1.88, -0.26, -3.07]}>
              <Mesh
                activeColor={props.activeColor}
                paintMode={props.paintMode}
                modelColors={props.modelColors}
                modelColorsRef={props.modelColorsRef}
                name="R_KNEE_SKULL"
                lightOne={props.lightOne}
                geometry={nodes.R_KNEE_SKULL.geometry}
                position={[-0.3, -0.12, 0.43]}
                rotation={[-2.92, 0, 3.13]}
                scale={[0.24, 0.24, 0.24]}
              />
              <Mesh
                activeColor={props.activeColor}
                paintMode={props.paintMode}
                modelColors={props.modelColors}
                modelColorsRef={props.modelColorsRef}
                name="R_KNEE_SKULL001"
                lightOne={props.lightOne}
                geometry={nodes.R_KNEE_SKULL001.geometry}
                position={[-0.3, -0.12, 0.43]}
                rotation={[-2.92, 0, 3.13]}
                scale={[0.24, 0.24, 0.24]}
              />
              <Mesh
                activeColor={props.activeColor}
                paintMode={props.paintMode}
                modelColors={props.modelColors}
                modelColorsRef={props.modelColorsRef}
                name="R_KNEE_SKULL002"
                lightOne={props.lightOne}
                geometry={nodes.R_KNEE_SKULL002.geometry}
                position={[-0.3, -0.12, 0.43]}
                rotation={[-2.92, 0, 3.13]}
                scale={[0.24, 0.24, 0.24]}
              />
            </group>
            <group position={[0, 0.43, 0]} rotation={[0.34, 0.3, 1.45]}>
              <Mesh
                activeColor={props.activeColor}
                paintMode={props.paintMode}
                modelColors={props.modelColors}
                modelColorsRef={props.modelColorsRef}
                name="R_LEG_ARMOR"
                lightOne={props.lightOne}
                geometry={nodes.R_LEG_ARMOR.geometry}
                position={[-0.47, -0.18, 0.2]}
                rotation={[2.2, 1.31, 2.14]}
                scale={[0.24, 0.24, 0.24]}
              />
            </group>
            <Mesh
              activeColor={props.activeColor}
              paintMode={props.paintMode}
              modelColors={props.modelColors}
              modelColorsRef={props.modelColorsRef}
              name="R_THIGH"
              lightOne={props.lightOne}
              geometry={nodes.R_THIGH.geometry}
              position={[0.18, -0.07, -0.01]}
              rotation={[-1.48, 0.27, -0.02]}
              scale={[0.24, 0.24, 0.24]}
            />
          </group>
          <Mesh
            activeColor={props.activeColor}
            paintMode={props.paintMode}
            modelColors={props.modelColors}
            modelColorsRef={props.modelColorsRef}
            name="WAIST_NO_BELT"
            lightOne={props.lightOne}
            geometry={nodes.WAIST_NO_BELT.geometry}
            position={[0, 0.09, 0.03]}
            rotation={[1.32, 0, 0]}
            scale={[0.24, 0.24, 0.24]}
          />
          <Mesh
            activeColor={props.activeColor}
            paintMode={props.paintMode}
            modelColors={props.modelColors}
            modelColorsRef={props.modelColorsRef}
            name="WAIST_NO_BELT001"
            lightOne={props.lightOne}
            geometry={nodes.WAIST_NO_BELT001.geometry}
            position={[0, 0.09, 0.03]}
            rotation={[1.32, 0, 0]}
            scale={[0.24, 0.24, 0.24]}
          />
          <Mesh
            activeColor={props.activeColor}
            paintMode={props.paintMode}
            modelColors={props.modelColors}
            modelColorsRef={props.modelColorsRef}
            name="WAIST_NO_BELT002"
            lightOne={props.lightOne}
            geometry={nodes.WAIST_NO_BELT002.geometry}
            position={[0, 0.09, 0.03]}
            rotation={[1.32, 0, 0]}
            scale={[0.24, 0.24, 0.24]}
          />
          <Mesh
            activeColor={props.activeColor}
            paintMode={props.paintMode}
            modelColors={props.modelColors}
            modelColorsRef={props.modelColorsRef}
            name="WAIST_NO_BELT003"
            lightOne={props.lightOne}
            geometry={nodes.WAIST_NO_BELT003.geometry}
            position={[0, 0.09, 0.03]}
            rotation={[1.32, 0, 0]}
            scale={[0.24, 0.24, 0.24]}
          />
          <Mesh
            activeColor={props.activeColor}
            paintMode={props.paintMode}
            modelColors={props.modelColors}
            modelColorsRef={props.modelColorsRef}
            name="WAIST_NO_BELT004"
            lightOne={props.lightOne}
            geometry={nodes.WAIST_NO_BELT004.geometry}
            position={[0, 0.09, 0.03]}
            rotation={[1.32, 0, 0]}
            scale={[0.24, 0.24, 0.24]}
          />
        </group>
        <Mesh
          activeColor={props.activeColor}
          paintMode={props.paintMode}
          modelColors={props.modelColors}
          modelColorsRef={props.modelColorsRef}
          name="L_ELBOW_MESH"
          lightOne={props.lightOne}
          geometry={nodes.L_ELBOW_MESH.geometry}
          position={[0, 1.09, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.24}
        />
        <Mesh
          activeColor={props.activeColor}
          paintMode={props.paintMode}
          modelColors={props.modelColors}
          modelColorsRef={props.modelColorsRef}
          name="L_FOOT_FLAT"
          lightOne={props.lightOne}
          geometry={nodes.L_FOOT_FLAT.geometry}
          position={[0, 1.09, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.24}
        />
        <Mesh
          activeColor={props.activeColor}
          paintMode={props.paintMode}
          modelColors={props.modelColors}
          modelColorsRef={props.modelColorsRef}
          name="L_HAND_GLOVE_MESH001"
          lightOne={props.lightOne}
          geometry={nodes.L_HAND_GLOVE_MESH001.geometry}
          position={[0.08, 1.18, -0.23]}
          rotation={[1.75, 0, 0.44]}
          scale={[0.24, 0.24, 0.24]}
        />
        <Mesh
          activeColor={props.activeColor}
          paintMode={props.paintMode}
          modelColors={props.modelColors}
          modelColorsRef={props.modelColorsRef}
          name="L_KNEE_MESH001"
          lightOne={props.lightOne}
          geometry={nodes.L_KNEE_MESH001.geometry}
          position={[0, 1.07, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.24}
        />
        <Mesh
          activeColor={props.activeColor}
          paintMode={props.paintMode}
          modelColors={props.modelColors}
          modelColorsRef={props.modelColorsRef}
          name="L_SHOULDER_MESH"
          lightOne={props.lightOne}
          geometry={nodes.L_SHOULDER_MESH.geometry}
          position={[0, 1.09, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.24}
        />
        <Mesh
          activeColor={props.activeColor}
          paintMode={props.paintMode}
          modelColors={props.modelColors}
          modelColorsRef={props.modelColorsRef}
          name="L_THIGH_MESH"
          lightOne={props.lightOne}
          geometry={nodes.L_THIGH_MESH.geometry}
          position={[0, 1.09, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.24}
        />
        <Mesh
          activeColor={props.activeColor}
          paintMode={props.paintMode}
          modelColors={props.modelColors}
          modelColorsRef={props.modelColorsRef}
          name="R_ELBOW_MESH"
          lightOne={props.lightOne}
          geometry={nodes.R_ELBOW_MESH.geometry}
          position={[0, 1.09, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.24}
        />
        <Mesh
          activeColor={props.activeColor}
          paintMode={props.paintMode}
          modelColors={props.modelColors}
          modelColorsRef={props.modelColorsRef}
          name="R_FOOT_FLAT"
          lightOne={props.lightOne}
          geometry={nodes.R_FOOT_FLAT.geometry}
          position={[0, 1.09, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.24}
        />
        <Mesh
          activeColor={props.activeColor}
          paintMode={props.paintMode}
          modelColors={props.modelColors}
          modelColorsRef={props.modelColorsRef}
          name="R_KNEE_MESH001"
          lightOne={props.lightOne}
          geometry={nodes.R_KNEE_MESH001.geometry}
          position={[0, 1.07, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.24}
        />
        <Mesh
          activeColor={props.activeColor}
          paintMode={props.paintMode}
          modelColors={props.modelColors}
          modelColorsRef={props.modelColorsRef}
          name="R_SHOUDLER_MESH"
          lightOne={props.lightOne}
          geometry={nodes.R_SHOUDLER_MESH.geometry}
          position={[0, 1.09, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.24}
        />
        <Mesh
          activeColor={props.activeColor}
          paintMode={props.paintMode}
          modelColors={props.modelColors}
          modelColorsRef={props.modelColorsRef}
          name="R_THIGH_MESH"
          lightOne={props.lightOne}
          geometry={nodes.R_THIGH_MESH.geometry}
          position={[0, 1.09, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.24}
        />
      </group>
      <Mesh
        activeColor={props.activeColor}
        paintMode={props.paintMode}
        modelColors={props.modelColors}
        modelColorsRef={props.modelColorsRef}
        name="R_KNEE_SKULL005"
        lightOne={props.lightOne}
        geometry={nodes.R_KNEE_SKULL005.geometry}
        rotation={[Math.PI / 2, 0, 0]}
        scale={5}
      />
      <Mesh
        activeColor={props.activeColor}
        paintMode={props.paintMode}
        modelColors={props.modelColors}
        modelColorsRef={props.modelColorsRef}
        name="R_KNEE_SKULL004"
        lightOne={props.lightOne}
        geometry={nodes.R_KNEE_SKULL004.geometry}
        rotation={[Math.PI / 2, 0, 0]}
        scale={5}
      />
      <Mesh
        activeColor={props.activeColor}
        paintMode={props.paintMode}
        modelColors={props.modelColors}
        modelColorsRef={props.modelColorsRef}
        name="R_KNEE_SKULL003"
        lightOne={props.lightOne}
        geometry={nodes.R_KNEE_SKULL003.geometry}
        rotation={[Math.PI / 2, 0, 0]}
        scale={5}
      />
    </group>
  );
}
