/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react';
import { useGLTF } from '@react-three/drei';
import Mesh from '../Mesh';
import edging from '../Base/edging.png';

export default function Model({ props }) {
  const group = useRef();
  const { nodes } = useGLTF(`${props.gltfIn}`);
  if (!nodes) {
    return 'Loading';
  }

  return (
    <group ref={group} {...props} dispose={null}>
      <Mesh
        activeColor={props.activeColor}
        paintMode={props.paintMode}
        modelColors={props.modelColors}
        modelColorsRef={props.modelColorsRef}
        name="Cylinder"
        lightOne={props.lightOne}
        geometry={nodes.Cylinder.geometry}
        scale={[4.05, -0.34, 4.05]}
        texture={edging}
      />
      <Mesh
        activeColor={props.activeColor}
        paintMode={props.paintMode}
        modelColors={props.modelColors}
        modelColorsRef={props.modelColorsRef}
        name="Cylinder001"
        lightOne={props.lightOne}
        geometry={nodes.Cylinder001.geometry}
        position={[0, 0.37, 0]}
        scale={[3.73, -0.05, 3.73]}
        texture={edging}
      />
    </group>
  );
}
