/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react';
import { useGLTF } from '@react-three/drei';
import Mesh from '../Mesh';
export default function Model({ props }) {
  const group = useRef();

  const { nodes } = useGLTF(`${props.gltfIn}`);

  return (
    <group ref={group} {...props} dispose={null}>
      <Mesh
        activeColor={props.activeColor}
        paintMode={props.paintMode}
        modelColors={props.modelColors}
        modelColorsRef={props.modelColorsRef}
        name="topStandard001"
        lightOne={props.lightOne}
        geometry={nodes.topStandard001.geometry}
        position={[0, 0.41, 0]}
        scale={[3.73, -0.05, 3.73]}
      />
      <Mesh
        activeColor={props.activeColor}
        paintMode={props.paintMode}
        modelColors={props.modelColors}
        modelColorsRef={props.modelColorsRef}
        name="SM_Small_Rock_06_Group5248015"
        lightOne={props.lightOne}
        geometry={nodes.SM_Small_Rock_06_Group5248015.geometry}
        position={[0, 0.3, -1.64]}
        rotation={[1.76, 0.99, 0.26]}
      />
      <Mesh
        activeColor={props.activeColor}
        paintMode={props.paintMode}
        modelColors={props.modelColors}
        modelColorsRef={props.modelColorsRef}
        name="SM_Small_Rock_06_Group5248001"
        lightOne={props.lightOne}
        geometry={nodes.SM_Small_Rock_06_Group5248001.geometry}
        position={[2.33, 0.3, -1.64]}
        rotation={[Math.PI / 2, 0, -1.13]}
        scale={1.3}
      />
      <Mesh
        activeColor={props.activeColor}
        paintMode={props.paintMode}
        modelColors={props.modelColors}
        modelColorsRef={props.modelColorsRef}
        name="SM_Small_Rock_06_Group5248002"
        lightOne={props.lightOne}
        geometry={nodes.SM_Small_Rock_06_Group5248002.geometry}
        position={[0, 0.3, 1.61]}
        rotation={[0.26, -0.87, -1.34]}
        scale={2.34}
      />
      <Mesh
        activeColor={props.activeColor}
        paintMode={props.paintMode}
        modelColors={props.modelColors}
        modelColorsRef={props.modelColorsRef}
        name="SM_Small_Rock_06_Group5248003"
        lightOne={props.lightOne}
        geometry={nodes.SM_Small_Rock_06_Group5248003.geometry}
        position={[3.12, 0.3, -0.27]}
        rotation={[Math.PI / 2, 0, 1.06]}
        scale={1.12}
      />
      <Mesh
        activeColor={props.activeColor}
        paintMode={props.paintMode}
        modelColors={props.modelColors}
        modelColorsRef={props.modelColorsRef}
        name="SM_Small_Rock_06_Group5248004"
        lightOne={props.lightOne}
        geometry={nodes.SM_Small_Rock_06_Group5248004.geometry}
        position={[-1.78, 0.3, -1.64]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <Mesh
        activeColor={props.activeColor}
        paintMode={props.paintMode}
        modelColors={props.modelColors}
        modelColorsRef={props.modelColorsRef}
        name="SM_Flat_Rock_02_Group46434005"
        lightOne={props.lightOne}
        geometry={nodes.SM_Flat_Rock_02_Group46434005.geometry}
        position={[2.89, 0.41, -1.05]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <Mesh
        activeColor={props.activeColor}
        paintMode={props.paintMode}
        modelColors={props.modelColors}
        modelColorsRef={props.modelColorsRef}
        name="SM_Flat_Rock_02_Group46434001"
        lightOne={props.lightOne}
        geometry={nodes.SM_Flat_Rock_02_Group46434001.geometry}
        position={[-1.53, 0.43, 2.14]}
        rotation={[Math.PI / 2, 0, -2.11]}
      />
      <Mesh
        activeColor={props.activeColor}
        paintMode={props.paintMode}
        modelColors={props.modelColors}
        modelColorsRef={props.modelColorsRef}
        name="SM_Rock_03_Group5248012"
        lightOne={props.lightOne}
        geometry={nodes.SM_Rock_03_Group5248012.geometry}
        position={[2.29, 0.45, 0]}
        rotation={[1.18, 0, 0]}
      />
      <Mesh
        activeColor={props.activeColor}
        paintMode={props.paintMode}
        modelColors={props.modelColors}
        modelColorsRef={props.modelColorsRef}
        name="topStandard002"
        lightOne={props.lightOne}
        geometry={nodes.topStandard002.geometry}
        position={[0, 0.41, 0]}
        scale={[3.73, -0.05, 3.73]}
      />
      <Mesh
        activeColor={props.activeColor}
        paintMode={props.paintMode}
        modelColors={props.modelColors}
        modelColorsRef={props.modelColorsRef}
        name="SM_Rock_03_Group5248001"
        lightOne={props.lightOne}
        geometry={nodes.SM_Rock_03_Group5248001.geometry}
        position={[-1.9, 0.45, -2.35]}
        rotation={[1.58, -0.39, 1.61]}
      />
    </group>
  );
}
