export const paints = [
  {
    name: 'Leadbelcher',
    color: '#848484',
    metal: true,
    company: 'Games Workshop',
  },
  {
    name: 'Stormhost Silver',
    color: '#ced2d4',
    metal: true,
    company: 'Games Workshop',
  },
  {
    name: 'Runefang Steel',
    color: '#a9afb4',
    metal: true,
    company: 'Games Workshop',
  },
  {
    name: 'Ironbreaker',
    color: '#6a7071',
    metal: true,
    company: 'Games Workshop',
  },
  {
    name: 'Liberator Gold',
    color: '#c89e5b',
    metal: true,
    company: 'Games Workshop',
  },
  {
    name: 'auricArmour',
    color: '#f5b13d',
    metal: true,
    company: 'Games Workshop',
  },
  {
    name: `Gehenna's Gold`,
    color: '#b55513',
    metal: true,
    company: 'Games Workshop',
  },
  {
    name: `Fulgurite Copper`,
    color: '#c17a3c',
    metal: true,
    company: 'Games Workshop',
  },
  {
    name: `Hashut Copper`,
    color: '#a97753',
    metal: true,
    company: 'Games Workshop',
  },
  {
    name: `Skullcrusher Brass`,
    color: '#e9b860',
    metal: true,
    company: 'Games Workshop',
  },
  {
    name: `Brass Scorpion`,
    color: '#8b431e',
    metal: true,
    company: 'Games Workshop',
  },
  {
    name: `Sycorax Bronze`,
    color: '#a28167',
    metal: true,
    company: 'Games Workshop',
  },
  {
    name: `Castellax Bronze`,
    color: '#98542c',
    metal: true,
    company: 'Games Workshop',
  },
  {
    name: `Canoptek Alloy`,
    color: '#b49b95',
    metal: true,
    company: 'Games Workshop',
  },
  {
    name: 'White Scar',
    color: '#fff',
    link: 'https://www.games-workshop.com/en-GB/Layer-White-Scar-2019',
    company: 'Games Workshop',
  },
  { name: 'Ulthuan Grey', color: '#c4ddd5', company: 'Games Workshop' },
  { name: 'Dorn Yellow', color: '#fff55a', company: 'Games Workshop' },
  { name: 'Phalanx Yellow', color: '#ffe200', company: 'Games Workshop' },
  { name: 'Flash Gitz Yellow', color: '#fff300', company: 'Games Workshop' },
  { name: 'Yriel Yellow', color: '#ffd900', company: 'Games Workshop' },
  { name: 'Lugganath Orange', color: '#f69b82', company: 'Games Workshop' },
  { name: 'Fire Dragon Bright', color: '#f4874e', company: 'Games Workshop' },
  { name: 'Troll Slayer Orange', color: '#f16c23', company: 'Games Workshop' },
  { name: 'Squig Orange', color: '#a74d42', company: 'Games Workshop' },
  { name: 'Wild Rider Red', color: '#e82e1b', company: 'Games Workshop' },
  { name: 'Evil Sunz Scarlet', color: '#c01411', company: 'Games Workshop' },
  { name: 'Wazdakka Red', color: '#880804', company: 'Games Workshop' },
  { name: 'Word Bearers Red', color: '#620104', company: 'Games Workshop' },
  { name: 'Fulgrim Pink', color: '#f3abca', company: 'Games Workshop' },
  { name: `Emperor's Children`, color: '#b74073', company: 'Games Workshop' },
  { name: `Pink Horror`, color: '#8e2757', company: 'Games Workshop' },
  { name: `Slaanesh Grey`, color: '#8b8893', company: 'Games Workshop' },
  { name: `Warpfiend Grey`, color: '#66656e', company: 'Games Workshop' },
  { name: `Dechala Lilac`, color: '#b598c9', company: 'Games Workshop' },
  { name: `Kakophoni Purple`, color: '#8869ae', company: 'Games Workshop' },
  { name: `Genestealer Purple`, color: '#7658a5', company: 'Games Workshop' },
  { name: `Xereus Purple`, color: '#47125a', company: 'Games Workshop' },
  { name: `Blue Horror`, color: '#9eb5ce', company: 'Games Workshop' },
  { name: `Hoeth Blue`, color: '#4c78af', company: 'Games Workshop' },
  { name: `Lothern Blue`, color: '#2c9bcc', company: 'Games Workshop' },
  { name: `Calgar Blue`, color: '#2a497f', company: 'Games Workshop' },
  { name: `Teclis Blue`, color: '#3877bf', company: 'Games Workshop' },
  { name: `Alaitoc Blue`, color: '#2f4f85', company: 'Games Workshop' },
  { name: `Altdorf Guard Blue`, color: '#2d4696', company: 'Games Workshop' },
  { name: `Baharroth Blue`, color: '#54bdca', company: 'Games Workshop' },
  { name: `Temple Guard Blue`, color: '#239489', company: 'Games Workshop' },
  {
    name: `Ahriman Blue`,
    color: '#00708a',
    metal: true,
    company: 'Games Workshop',
  },
  { name: `Sotek Green`, color: '#0b6371', company: 'Games Workshop' },
  { name: `Gauss Blaster Green`, color: '#7fc1a5', company: 'Games Workshop' },
  { name: `Sybarite Green`, color: '#17a166', company: 'Games Workshop' },
  { name: `Kabalite Green`, color: '#008962', company: 'Games Workshop' },
  { name: `Nurgling Green`, color: '#7e975e', company: 'Games Workshop' },
  { name: `Elysian Green`, color: '#6b8c37', company: 'Games Workshop' },
  { name: `Ogryn Camo`, color: '#96a648', company: 'Games Workshop' },
  { name: `Straken Green`, color: '#597f1c', company: 'Games Workshop' },
  { name: `Loren Forest`, color: '#486c25', company: 'Games Workshop' },
  { name: `Sons of Horus Green`, color: '#00545e', company: 'Games Workshop' },
  { name: `Vulkan Green`, color: '#223c2e', company: 'Games Workshop' },
  { name: `Skarsnik Green`, color: '#588f6b', company: 'Games Workshop' },
  { name: `Moot Green`, color: '#3daf44', company: 'Games Workshop' },
  { name: `Warboss Green`, color: '#317e57', company: 'Games Workshop' },
  { name: `Warpstone Glow`, color: '#0f702a', company: 'Games Workshop' },
  { name: `Screaming Skull`, color: '#b9c099', company: 'Games Workshop' },
  { name: `Ushabti Bone`, color: '#aba173', company: 'Games Workshop' },
  { name: `Krieg Khaki`, color: '#bcbb7e', company: 'Games Workshop' },
  { name: `Karak Stone`, color: '#b7945c', company: 'Games Workshop' },
  { name: `Baneblade Brown`, color: '#8f7c68', company: 'Games Workshop' },
  { name: `Gorthor Brown`, color: '#5f463f', company: 'Games Workshop' },
  { name: `Zamesi Desert`, color: '#d89d1b', company: 'Games Workshop' },
  { name: `Tallarn Sand`, color: '#a07409', company: 'Games Workshop' },
  { name: `Deathclaw Brown`, color: '#af634f', company: 'Games Workshop' },
  { name: `Balor Brown`, color: '#875408', company: 'Games Workshop' },
  { name: `Tau Light Ochre`, color: '#bc6b10', company: 'Games Workshop' },
  { name: `Skrag Brown`, color: '#8b4806', company: 'Games Workshop' },
  { name: `Tuskgor Fur`, color: '#863231', company: 'Games Workshop' },
  { name: `Doombull Brown`, color: '#570003', company: 'Games Workshop' },
  { name: `Pallid Wych Flesh`, color: '#caccbb', company: 'Games Workshop' },
  { name: `Deepkin Flesh`, color: '#a9b79f', company: 'Games Workshop' },
  { name: `Flayed One Flesh`, color: '#eec483', company: 'Games Workshop' },
  { name: `Ungor Flesh`, color: '#d1a560', company: 'Games Workshop' },
  { name: `Kislev Flesh`, color: '#d1a570', company: 'Games Workshop' },
  { name: `Bestigor Flesh`, color: '#d08951', company: 'Games Workshop' },
  { name: `Cadian Fleshtone`, color: '#c47652', company: 'Games Workshop' },
  { name: `Knight-Questor Flesh`, color: '#996563', company: 'Games Workshop' },
  { name: `Bloodreaver Flesh`, color: '#6a4848', company: 'Games Workshop' },
  { name: `Fenrisian Grey`, color: '#6d94b3', company: 'Games Workshop' },
  { name: `Russ Grey`, color: '#507085', company: 'Games Workshop' },
  { name: `Thunderhawk Blue`, color: '#396a70', company: 'Games Workshop' },
  { name: `Dark Reaper`, color: '#354d4c', company: 'Games Workshop' },
  { name: `Administratum Grey`, color: '#989c94', company: 'Games Workshop' },
  { name: `Dawnstone`, color: '#697068', company: 'Games Workshop' },
  { name: `Stormvermin Fur`, color: '#6d655f', company: 'Games Workshop' },
  { name: `Eshin Grey`, color: '#484b4e', company: 'Games Workshop' },
  { name: `Skavenblight Dinge`, color: '#45413b', company: 'Games Workshop' },
  {
    name: 'Warplock Bronze',
    color: '#9e573c',
    metal: true,
    company: 'Games Workshop',
  },
  {
    name: 'Retributor Armour',
    color: '#e6b351',
    metal: true,
    company: 'Games Workshop',
  },
  { name: 'DM Dark', color: '#39354e', company: 'Games Workshop' },
  { name: 'DM Main', color: '#7163b7', company: 'Games Workshop' },
  { name: 'DM Secondary', color: '#d0b58e', company: 'Games Workshop' },
  {
    name: 'calgarBlue',
    color: '#2a497f',
    company: 'Games Workshop',
  },
  { name: 'The Fang', color: '#405b71', company: 'Games Workshop' },
  { name: 'Thousand Sons Blue', color: '#00506f', company: 'Games Workshop' },
  { name: 'Higaaran', color: '#6280ae', company: 'Games Workshop' },
  { name: 'Ahriman Blue', color: '#00708a', company: 'Games Workshop' },

  { name: 'averlandSunset', color: '#fbb81c', company: 'Games Workshop' },
  { name: 'dornYellow', color: '#fff55a', company: 'Games Workshop' },
  { name: 'Phalanx Yellow', color: '#ffe200', company: 'Games Workshop' },
  { name: 'Yriel Yellow', color: '#ffd900', company: 'Games Workshop' },
  {
    name: 'mephistonRed',
    color: '#960b07',
    company: 'Games Workshop',
  },
  { name: 'Jokaero Orange', color: '#ed3814', company: 'Games Workshop' },
  { name: 'emperorsChildren', color: '#b74073', company: 'Games Workshop' },
  {
    name: 'abaddonBlack',
    color: '#111111',
    company: 'Games Workshop',
  },
  {
    name: 'white',
    color: '#fafafa',
    company: 'Games Workshop',
  },
  {
    name: 'xv88',
    color: '#6c4811',
    company: 'Games Workshop',
  },
  {
    name: 'darkAngel',
    color: '#002e2a',
    company: 'Games Workshop',
  },

  { name: 'wraithbone', color: '#dbd1b2', company: 'Games Workshop' },
  { name: 'nurglingGreen', color: '#7e975e', company: 'Games Workshop' },
  { name: 'orrukFlesh', color: '#8cc276', company: 'Games Workshop' },

  { name: 'Grey Seer', color: '#a2a5a7', company: 'Games Workshop' },
  { name: 'Celestra Grey', color: '#8ba3a3', company: 'Games Workshop' },

  {
    name: 'Mechanicus Standard Grey',
    color: '#39484a',
    company: 'Games Workshop',
  },
  { name: 'Death Korps Drab', color: '#3d4539', company: 'Games Workshop' },
  { name: 'Ulthuan Grey', color: '#c4ddd5', company: 'Games Workshop' },
  { name: 'Fenrisian Grey', color: '##6d94b3', company: 'Games Workshop' },
  { name: 'Eshin Grey', color: '#484b4e', company: 'Games Workshop' },
  { name: 'Russ Grey', color: '#507085', company: 'Games Workshop' },
  { name: 'Slaanesh Grey', color: '#8b8893', company: 'Games Workshop' },
  { name: 'Administratum Grey', color: '#989c94', company: 'Games Workshop' },
  { name: 'Dawnstone', color: '#697068', company: 'Games Workshop' },
  { name: 'Stormvermin Fur', color: '#6d655f', company: 'Games Workshop' },
  { name: 'Skavenblight Dinge', color: '#45413b', company: 'Games Workshop' },
  { name: 'Warpfiend Grey', color: '#66656e', company: 'Games Workshop' },
  { name: 'Brass Scorpion', color: '#c58040', company: 'Games Workshop' },
  { name: 'Khorne Red', color: '#650001', company: 'Games Workshop' },
  { name: 'Caliban Green', color: '#003d15', company: 'Games Workshop' },
  { name: 'Rhinox Hide', color: '#462f30', company: 'Games Workshop' },
  { name: 'Ionrach Skin', color: '#97a384', company: 'Games Workshop' },
  { name: 'Higaaran Orange', color: '#a8621e', company: 'Custom - Homeworld' },
  { name: 'Blank', color: 'fff', company: 'Games Workshop' },
];
