/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Janovich (https://sketchfab.com/janovich3D)
created: Fri Oct  1 18:38:21 2021
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/warhammer-40k-space-marine-650166abbb3448e9adece85e30b59c06
title: Warhammer 40K Space Marine
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

import Mesh from '../../Mesh';
export default function Model({ props }) {
  const group = useRef();
  const { nodes } = useGLTF(props.gltfIn);
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <Mesh
            activeColor={props.activeColor}
            paintMode={props.paintMode}
            modelColors={props.modelColors}
            modelColorsRef={props.modelColorsRef}
            name="Group7095_backpack1_0"
            lightOne={props.lightOne}
            geometry={nodes.Group7095_backpack1_0.geometry}
          />
          <Mesh
            activeColor={props.activeColor}
            paintMode={props.paintMode}
            modelColors={props.modelColors}
            modelColorsRef={props.modelColorsRef}
            name="pCube17_backpack1_0"
            lightOne={props.lightOne}
            geometry={nodes.pCube17_backpack1_0.geometry}
          />
          <Mesh
            activeColor={props.activeColor}
            paintMode={props.paintMode}
            modelColors={props.modelColors}
            modelColorsRef={props.modelColorsRef}
            name="polySurface1_backpack1_0"
            lightOne={props.lightOne}
            geometry={nodes.polySurface1_backpack1_0.geometry}
          />
          <Mesh
            activeColor={props.activeColor}
            paintMode={props.paintMode}
            modelColors={props.modelColors}
            modelColorsRef={props.modelColorsRef}
            name="pPlane13_details_0"
            lightOne={props.lightOne}
            geometry={nodes.pPlane13_details_0.geometry}
          />
          <Mesh
            activeColor={props.activeColor}
            paintMode={props.paintMode}
            modelColors={props.modelColors}
            modelColorsRef={props.modelColorsRef}
            name="pSphere4_backpack1_0"
            lightOne={props.lightOne}
            geometry={nodes.pSphere4_backpack1_0.geometry}
          />
          <Mesh
            activeColor={props.activeColor}
            paintMode={props.paintMode}
            modelColors={props.modelColors}
            modelColorsRef={props.modelColorsRef}
            name="pSphere5_backpack1_0"
            lightOne={props.lightOne}
            geometry={nodes.pSphere5_backpack1_0.geometry}
          />
        </group>
      </group>
    </group>
  );
}
